// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/operator_events.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.events.v1;

/**
 * <pre>
 * Сырой DLR — публикуется в operator.dlr. Operator SMPP Session Manager
 * публикует его из deliver_sm; Operator HTTP Gateway — из нормализованного
 * webhook-payload, в тот же формат (services_specifictaion.md §2.3a).
 * </pre>
 *
 * Protobuf type {@code mpp.events.v1.OperatorDlr}
 */
@com.google.protobuf.Generated
public final class OperatorDlr extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:mpp.events.v1.OperatorDlr)
    OperatorDlrOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "OperatorDlr");
  }
  // Use OperatorDlr.newBuilder() to construct.
  private OperatorDlr(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private OperatorDlr() {
    operatorId_ = "";
    protocol_ = 0;
    smscMessageId_ = "";
    rawStatus_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uz.mpp.platformcontracts.events.v1.OperatorEvents.internal_static_mpp_events_v1_OperatorDlr_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return uz.mpp.platformcontracts.events.v1.OperatorEvents.internal_static_mpp_events_v1_OperatorDlr_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uz.mpp.platformcontracts.events.v1.OperatorEvents.internal_static_mpp_events_v1_OperatorDlr_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uz.mpp.platformcontracts.events.v1.OperatorDlr.class, uz.mpp.platformcontracts.events.v1.OperatorDlr.Builder.class);
  }

  private int bitField0_;
  public static final int OPERATOR_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object operatorId_ = "";
  /**
   * <code>string operator_id = 1;</code>
   * @return The operatorId.
   */
  @java.lang.Override
  public java.lang.String getOperatorId() {
    java.lang.Object ref = operatorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      operatorId_ = s;
      return s;
    }
  }
  /**
   * <code>string operator_id = 1;</code>
   * @return The bytes for operatorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOperatorIdBytes() {
    java.lang.Object ref = operatorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      operatorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROTOCOL_FIELD_NUMBER = 2;
  private int protocol_ = 0;
  /**
   * <code>.mpp.common.v1.Protocol protocol = 2;</code>
   * @return The enum numeric value on the wire for protocol.
   */
  @java.lang.Override public int getProtocolValue() {
    return protocol_;
  }
  /**
   * <code>.mpp.common.v1.Protocol protocol = 2;</code>
   * @return The protocol.
   */
  @java.lang.Override public uz.mpp.platformcontracts.common.v1.Protocol getProtocol() {
    uz.mpp.platformcontracts.common.v1.Protocol result = uz.mpp.platformcontracts.common.v1.Protocol.forNumber(protocol_);
    return result == null ? uz.mpp.platformcontracts.common.v1.Protocol.UNRECOGNIZED : result;
  }

  public static final int SMSC_MESSAGE_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object smscMessageId_ = "";
  /**
   * <code>string smsc_message_id = 3;</code>
   * @return The smscMessageId.
   */
  @java.lang.Override
  public java.lang.String getSmscMessageId() {
    java.lang.Object ref = smscMessageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      smscMessageId_ = s;
      return s;
    }
  }
  /**
   * <code>string smsc_message_id = 3;</code>
   * @return The bytes for smscMessageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSmscMessageIdBytes() {
    java.lang.Object ref = smscMessageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      smscMessageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEGMENT_ID_FIELD_NUMBER = 4;
  private int segmentId_ = 0;
  /**
   * <code>int32 segment_id = 4;</code>
   * @return The segmentId.
   */
  @java.lang.Override
  public int getSegmentId() {
    return segmentId_;
  }

  public static final int RAW_STATUS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object rawStatus_ = "";
  /**
   * <pre>
   * Код статуса в терминологии оператора, до нормализации DLR Manager'ом.
   * </pre>
   *
   * <code>string raw_status = 5;</code>
   * @return The rawStatus.
   */
  @java.lang.Override
  public java.lang.String getRawStatus() {
    java.lang.Object ref = rawStatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rawStatus_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Код статуса в терминологии оператора, до нормализации DLR Manager'ом.
   * </pre>
   *
   * <code>string raw_status = 5;</code>
   * @return The bytes for rawStatus.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRawStatusBytes() {
    java.lang.Object ref = rawStatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rawStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECEIVED_AT_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp receivedAt_;
  /**
   * <code>.google.protobuf.Timestamp received_at = 6;</code>
   * @return Whether the receivedAt field is set.
   */
  @java.lang.Override
  public boolean hasReceivedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp received_at = 6;</code>
   * @return The receivedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getReceivedAt() {
    return receivedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : receivedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp received_at = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getReceivedAtOrBuilder() {
    return receivedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : receivedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(operatorId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, operatorId_);
    }
    if (protocol_ != uz.mpp.platformcontracts.common.v1.Protocol.PROTOCOL_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, protocol_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(smscMessageId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, smscMessageId_);
    }
    if (segmentId_ != 0) {
      output.writeInt32(4, segmentId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rawStatus_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, rawStatus_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getReceivedAt());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(operatorId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, operatorId_);
    }
    if (protocol_ != uz.mpp.platformcontracts.common.v1.Protocol.PROTOCOL_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, protocol_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(smscMessageId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, smscMessageId_);
    }
    if (segmentId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, segmentId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rawStatus_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, rawStatus_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getReceivedAt());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uz.mpp.platformcontracts.events.v1.OperatorDlr)) {
      return super.equals(obj);
    }
    uz.mpp.platformcontracts.events.v1.OperatorDlr other = (uz.mpp.platformcontracts.events.v1.OperatorDlr) obj;

    if (!getOperatorId()
        .equals(other.getOperatorId())) return false;
    if (protocol_ != other.protocol_) return false;
    if (!getSmscMessageId()
        .equals(other.getSmscMessageId())) return false;
    if (getSegmentId()
        != other.getSegmentId()) return false;
    if (!getRawStatus()
        .equals(other.getRawStatus())) return false;
    if (hasReceivedAt() != other.hasReceivedAt()) return false;
    if (hasReceivedAt()) {
      if (!getReceivedAt()
          .equals(other.getReceivedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OPERATOR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOperatorId().hashCode();
    hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
    hash = (53 * hash) + protocol_;
    hash = (37 * hash) + SMSC_MESSAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSmscMessageId().hashCode();
    hash = (37 * hash) + SEGMENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSegmentId();
    hash = (37 * hash) + RAW_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getRawStatus().hashCode();
    if (hasReceivedAt()) {
      hash = (37 * hash) + RECEIVED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getReceivedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uz.mpp.platformcontracts.events.v1.OperatorDlr parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorDlr parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorDlr parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorDlr parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorDlr parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorDlr parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorDlr parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorDlr parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static uz.mpp.platformcontracts.events.v1.OperatorDlr parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static uz.mpp.platformcontracts.events.v1.OperatorDlr parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorDlr parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorDlr parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uz.mpp.platformcontracts.events.v1.OperatorDlr prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Сырой DLR — публикуется в operator.dlr. Operator SMPP Session Manager
   * публикует его из deliver_sm; Operator HTTP Gateway — из нормализованного
   * webhook-payload, в тот же формат (services_specifictaion.md §2.3a).
   * </pre>
   *
   * Protobuf type {@code mpp.events.v1.OperatorDlr}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mpp.events.v1.OperatorDlr)
      uz.mpp.platformcontracts.events.v1.OperatorDlrOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uz.mpp.platformcontracts.events.v1.OperatorEvents.internal_static_mpp_events_v1_OperatorDlr_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uz.mpp.platformcontracts.events.v1.OperatorEvents.internal_static_mpp_events_v1_OperatorDlr_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uz.mpp.platformcontracts.events.v1.OperatorDlr.class, uz.mpp.platformcontracts.events.v1.OperatorDlr.Builder.class);
    }

    // Construct using uz.mpp.platformcontracts.events.v1.OperatorDlr.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetReceivedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      operatorId_ = "";
      protocol_ = 0;
      smscMessageId_ = "";
      segmentId_ = 0;
      rawStatus_ = "";
      receivedAt_ = null;
      if (receivedAtBuilder_ != null) {
        receivedAtBuilder_.dispose();
        receivedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uz.mpp.platformcontracts.events.v1.OperatorEvents.internal_static_mpp_events_v1_OperatorDlr_descriptor;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.events.v1.OperatorDlr getDefaultInstanceForType() {
      return uz.mpp.platformcontracts.events.v1.OperatorDlr.getDefaultInstance();
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.events.v1.OperatorDlr build() {
      uz.mpp.platformcontracts.events.v1.OperatorDlr result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.events.v1.OperatorDlr buildPartial() {
      uz.mpp.platformcontracts.events.v1.OperatorDlr result = new uz.mpp.platformcontracts.events.v1.OperatorDlr(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(uz.mpp.platformcontracts.events.v1.OperatorDlr result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.operatorId_ = operatorId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.protocol_ = protocol_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.smscMessageId_ = smscMessageId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.segmentId_ = segmentId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.rawStatus_ = rawStatus_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.receivedAt_ = receivedAtBuilder_ == null
            ? receivedAt_
            : receivedAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uz.mpp.platformcontracts.events.v1.OperatorDlr) {
        return mergeFrom((uz.mpp.platformcontracts.events.v1.OperatorDlr)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uz.mpp.platformcontracts.events.v1.OperatorDlr other) {
      if (other == uz.mpp.platformcontracts.events.v1.OperatorDlr.getDefaultInstance()) return this;
      if (!other.getOperatorId().isEmpty()) {
        operatorId_ = other.operatorId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.protocol_ != 0) {
        setProtocolValue(other.getProtocolValue());
      }
      if (!other.getSmscMessageId().isEmpty()) {
        smscMessageId_ = other.smscMessageId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getSegmentId() != 0) {
        setSegmentId(other.getSegmentId());
      }
      if (!other.getRawStatus().isEmpty()) {
        rawStatus_ = other.rawStatus_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasReceivedAt()) {
        mergeReceivedAt(other.getReceivedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              operatorId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              protocol_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              smscMessageId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              segmentId_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              rawStatus_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetReceivedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object operatorId_ = "";
    /**
     * <code>string operator_id = 1;</code>
     * @return The operatorId.
     */
    public java.lang.String getOperatorId() {
      java.lang.Object ref = operatorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operatorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string operator_id = 1;</code>
     * @return The bytes for operatorId.
     */
    public com.google.protobuf.ByteString
        getOperatorIdBytes() {
      java.lang.Object ref = operatorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operatorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string operator_id = 1;</code>
     * @param value The operatorId to set.
     * @return This builder for chaining.
     */
    public Builder setOperatorId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      operatorId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string operator_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperatorId() {
      operatorId_ = getDefaultInstance().getOperatorId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string operator_id = 1;</code>
     * @param value The bytes for operatorId to set.
     * @return This builder for chaining.
     */
    public Builder setOperatorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      operatorId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int protocol_ = 0;
    /**
     * <code>.mpp.common.v1.Protocol protocol = 2;</code>
     * @return The enum numeric value on the wire for protocol.
     */
    @java.lang.Override public int getProtocolValue() {
      return protocol_;
    }
    /**
     * <code>.mpp.common.v1.Protocol protocol = 2;</code>
     * @param value The enum numeric value on the wire for protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolValue(int value) {
      protocol_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.mpp.common.v1.Protocol protocol = 2;</code>
     * @return The protocol.
     */
    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.Protocol getProtocol() {
      uz.mpp.platformcontracts.common.v1.Protocol result = uz.mpp.platformcontracts.common.v1.Protocol.forNumber(protocol_);
      return result == null ? uz.mpp.platformcontracts.common.v1.Protocol.UNRECOGNIZED : result;
    }
    /**
     * <code>.mpp.common.v1.Protocol protocol = 2;</code>
     * @param value The protocol to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setProtocol(uz.mpp.platformcontracts.common.v1.Protocol value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      protocol_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.mpp.common.v1.Protocol protocol = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocol() {
      bitField0_ = (bitField0_ & ~0x00000002);
      protocol_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object smscMessageId_ = "";
    /**
     * <code>string smsc_message_id = 3;</code>
     * @return The smscMessageId.
     */
    public java.lang.String getSmscMessageId() {
      java.lang.Object ref = smscMessageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        smscMessageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string smsc_message_id = 3;</code>
     * @return The bytes for smscMessageId.
     */
    public com.google.protobuf.ByteString
        getSmscMessageIdBytes() {
      java.lang.Object ref = smscMessageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        smscMessageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string smsc_message_id = 3;</code>
     * @param value The smscMessageId to set.
     * @return This builder for chaining.
     */
    public Builder setSmscMessageId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      smscMessageId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string smsc_message_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSmscMessageId() {
      smscMessageId_ = getDefaultInstance().getSmscMessageId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string smsc_message_id = 3;</code>
     * @param value The bytes for smscMessageId to set.
     * @return This builder for chaining.
     */
    public Builder setSmscMessageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      smscMessageId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int segmentId_ ;
    /**
     * <code>int32 segment_id = 4;</code>
     * @return The segmentId.
     */
    @java.lang.Override
    public int getSegmentId() {
      return segmentId_;
    }
    /**
     * <code>int32 segment_id = 4;</code>
     * @param value The segmentId to set.
     * @return This builder for chaining.
     */
    public Builder setSegmentId(int value) {

      segmentId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 segment_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSegmentId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      segmentId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object rawStatus_ = "";
    /**
     * <pre>
     * Код статуса в терминологии оператора, до нормализации DLR Manager'ом.
     * </pre>
     *
     * <code>string raw_status = 5;</code>
     * @return The rawStatus.
     */
    public java.lang.String getRawStatus() {
      java.lang.Object ref = rawStatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rawStatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Код статуса в терминологии оператора, до нормализации DLR Manager'ом.
     * </pre>
     *
     * <code>string raw_status = 5;</code>
     * @return The bytes for rawStatus.
     */
    public com.google.protobuf.ByteString
        getRawStatusBytes() {
      java.lang.Object ref = rawStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rawStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Код статуса в терминологии оператора, до нормализации DLR Manager'ом.
     * </pre>
     *
     * <code>string raw_status = 5;</code>
     * @param value The rawStatus to set.
     * @return This builder for chaining.
     */
    public Builder setRawStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      rawStatus_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Код статуса в терминологии оператора, до нормализации DLR Manager'ом.
     * </pre>
     *
     * <code>string raw_status = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRawStatus() {
      rawStatus_ = getDefaultInstance().getRawStatus();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Код статуса в терминологии оператора, до нормализации DLR Manager'ом.
     * </pre>
     *
     * <code>string raw_status = 5;</code>
     * @param value The bytes for rawStatus to set.
     * @return This builder for chaining.
     */
    public Builder setRawStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      rawStatus_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp receivedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> receivedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp received_at = 6;</code>
     * @return Whether the receivedAt field is set.
     */
    public boolean hasReceivedAt() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp received_at = 6;</code>
     * @return The receivedAt.
     */
    public com.google.protobuf.Timestamp getReceivedAt() {
      if (receivedAtBuilder_ == null) {
        return receivedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : receivedAt_;
      } else {
        return receivedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp received_at = 6;</code>
     */
    public Builder setReceivedAt(com.google.protobuf.Timestamp value) {
      if (receivedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        receivedAt_ = value;
      } else {
        receivedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp received_at = 6;</code>
     */
    public Builder setReceivedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (receivedAtBuilder_ == null) {
        receivedAt_ = builderForValue.build();
      } else {
        receivedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp received_at = 6;</code>
     */
    public Builder mergeReceivedAt(com.google.protobuf.Timestamp value) {
      if (receivedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          receivedAt_ != null &&
          receivedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getReceivedAtBuilder().mergeFrom(value);
        } else {
          receivedAt_ = value;
        }
      } else {
        receivedAtBuilder_.mergeFrom(value);
      }
      if (receivedAt_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp received_at = 6;</code>
     */
    public Builder clearReceivedAt() {
      bitField0_ = (bitField0_ & ~0x00000020);
      receivedAt_ = null;
      if (receivedAtBuilder_ != null) {
        receivedAtBuilder_.dispose();
        receivedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp received_at = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getReceivedAtBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetReceivedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp received_at = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getReceivedAtOrBuilder() {
      if (receivedAtBuilder_ != null) {
        return receivedAtBuilder_.getMessageOrBuilder();
      } else {
        return receivedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : receivedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp received_at = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetReceivedAtFieldBuilder() {
      if (receivedAtBuilder_ == null) {
        receivedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getReceivedAt(),
                getParentForChildren(),
                isClean());
        receivedAt_ = null;
      }
      return receivedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:mpp.events.v1.OperatorDlr)
  }

  // @@protoc_insertion_point(class_scope:mpp.events.v1.OperatorDlr)
  private static final uz.mpp.platformcontracts.events.v1.OperatorDlr DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uz.mpp.platformcontracts.events.v1.OperatorDlr();
  }

  public static uz.mpp.platformcontracts.events.v1.OperatorDlr getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OperatorDlr>
      PARSER = new com.google.protobuf.AbstractParser<OperatorDlr>() {
    @java.lang.Override
    public OperatorDlr parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OperatorDlr> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OperatorDlr> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uz.mpp.platformcontracts.events.v1.OperatorDlr getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

