// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/operator_events.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.events.v1;

@com.google.protobuf.Generated
public interface OperatorDlrOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.events.v1.OperatorDlr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string operator_id = 1;</code>
   * @return The operatorId.
   */
  java.lang.String getOperatorId();
  /**
   * <code>string operator_id = 1;</code>
   * @return The bytes for operatorId.
   */
  com.google.protobuf.ByteString
      getOperatorIdBytes();

  /**
   * <code>.mpp.common.v1.Protocol protocol = 2;</code>
   * @return The enum numeric value on the wire for protocol.
   */
  int getProtocolValue();
  /**
   * <code>.mpp.common.v1.Protocol protocol = 2;</code>
   * @return The protocol.
   */
  uz.mpp.platformcontracts.common.v1.Protocol getProtocol();

  /**
   * <code>string smsc_message_id = 3;</code>
   * @return The smscMessageId.
   */
  java.lang.String getSmscMessageId();
  /**
   * <code>string smsc_message_id = 3;</code>
   * @return The bytes for smscMessageId.
   */
  com.google.protobuf.ByteString
      getSmscMessageIdBytes();

  /**
   * <code>int32 segment_id = 4;</code>
   * @return The segmentId.
   */
  int getSegmentId();

  /**
   * <pre>
   * Код статуса в терминологии оператора, до нормализации DLR Manager'ом.
   * </pre>
   *
   * <code>string raw_status = 5;</code>
   * @return The rawStatus.
   */
  java.lang.String getRawStatus();
  /**
   * <pre>
   * Код статуса в терминологии оператора, до нормализации DLR Manager'ом.
   * </pre>
   *
   * <code>string raw_status = 5;</code>
   * @return The bytes for rawStatus.
   */
  com.google.protobuf.ByteString
      getRawStatusBytes();

  /**
   * <code>.google.protobuf.Timestamp received_at = 6;</code>
   * @return Whether the receivedAt field is set.
   */
  boolean hasReceivedAt();
  /**
   * <code>.google.protobuf.Timestamp received_at = 6;</code>
   * @return The receivedAt.
   */
  com.google.protobuf.Timestamp getReceivedAt();
  /**
   * <code>.google.protobuf.Timestamp received_at = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getReceivedAtOrBuilder();
}
