// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/operator_events.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.events.v1;

@com.google.protobuf.Generated
public interface OperatorSubmitAcceptedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.events.v1.OperatorSubmitAccepted)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message_id = 1;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <code>string message_id = 1;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>string stage_execution_id = 2;</code>
   * @return The stageExecutionId.
   */
  java.lang.String getStageExecutionId();
  /**
   * <code>string stage_execution_id = 2;</code>
   * @return The bytes for stageExecutionId.
   */
  com.google.protobuf.ByteString
      getStageExecutionIdBytes();

  /**
   * <code>string operator_id = 3;</code>
   * @return The operatorId.
   */
  java.lang.String getOperatorId();
  /**
   * <code>string operator_id = 3;</code>
   * @return The bytes for operatorId.
   */
  com.google.protobuf.ByteString
      getOperatorIdBytes();

  /**
   * <code>.mpp.common.v1.Protocol protocol = 4;</code>
   * @return The enum numeric value on the wire for protocol.
   */
  int getProtocolValue();
  /**
   * <code>.mpp.common.v1.Protocol protocol = 4;</code>
   * @return The protocol.
   */
  uz.mpp.platformcontracts.common.v1.Protocol getProtocol();

  /**
   * <pre>
   * Идентификатор сообщения на стороне SMSC/оператора, если доступен
   * сразу (не все операторы возвращают его синхронно).
   * </pre>
   *
   * <code>string smsc_message_id = 5;</code>
   * @return The smscMessageId.
   */
  java.lang.String getSmscMessageId();
  /**
   * <pre>
   * Идентификатор сообщения на стороне SMSC/оператора, если доступен
   * сразу (не все операторы возвращают его синхронно).
   * </pre>
   *
   * <code>string smsc_message_id = 5;</code>
   * @return The bytes for smscMessageId.
   */
  com.google.protobuf.ByteString
      getSmscMessageIdBytes();

  /**
   * <code>int32 segment_id = 6;</code>
   * @return The segmentId.
   */
  int getSegmentId();

  /**
   * <code>.google.protobuf.Timestamp submitted_at = 7;</code>
   * @return Whether the submittedAt field is set.
   */
  boolean hasSubmittedAt();
  /**
   * <code>.google.protobuf.Timestamp submitted_at = 7;</code>
   * @return The submittedAt.
   */
  com.google.protobuf.Timestamp getSubmittedAt();
  /**
   * <code>.google.protobuf.Timestamp submitted_at = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getSubmittedAtOrBuilder();

  /**
   * <pre>
   * DLR SLA конкретного оператора — используется для расчёта
   * expires_at в dlr_correlation (data_infrastructure_spec.md §1.8, §1.9a).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp correlation_expires_at = 8;</code>
   * @return Whether the correlationExpiresAt field is set.
   */
  boolean hasCorrelationExpiresAt();
  /**
   * <pre>
   * DLR SLA конкретного оператора — используется для расчёта
   * expires_at в dlr_correlation (data_infrastructure_spec.md §1.8, §1.9a).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp correlation_expires_at = 8;</code>
   * @return The correlationExpiresAt.
   */
  com.google.protobuf.Timestamp getCorrelationExpiresAt();
  /**
   * <pre>
   * DLR SLA конкретного оператора — используется для расчёта
   * expires_at в dlr_correlation (data_infrastructure_spec.md §1.8, §1.9a).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp correlation_expires_at = 8;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCorrelationExpiresAtOrBuilder();
}
