// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/operator_events.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.events.v1;

/**
 * <pre>
 * Принятый submit — публикуется в operator.submit.accepted как Operator SMPP
 * Session Manager, так и Operator HTTP Gateway в один и тот же формат;
 * downstream (DLR Correlation Writer, Delivery Reconciliation) не различает
 * протокол (HLD §11.3, data_infrastructure_spec.md §3).
 * </pre>
 *
 * Protobuf type {@code mpp.events.v1.OperatorSubmitAccepted}
 */
@com.google.protobuf.Generated
public final class OperatorSubmitAccepted extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:mpp.events.v1.OperatorSubmitAccepted)
    OperatorSubmitAcceptedOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "OperatorSubmitAccepted");
  }
  // Use OperatorSubmitAccepted.newBuilder() to construct.
  private OperatorSubmitAccepted(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private OperatorSubmitAccepted() {
    messageId_ = "";
    stageExecutionId_ = "";
    operatorId_ = "";
    protocol_ = 0;
    smscMessageId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uz.mpp.platformcontracts.events.v1.OperatorEvents.internal_static_mpp_events_v1_OperatorSubmitAccepted_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return uz.mpp.platformcontracts.events.v1.OperatorEvents.internal_static_mpp_events_v1_OperatorSubmitAccepted_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uz.mpp.platformcontracts.events.v1.OperatorEvents.internal_static_mpp_events_v1_OperatorSubmitAccepted_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted.class, uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted.Builder.class);
  }

  private int bitField0_;
  public static final int MESSAGE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object messageId_ = "";
  /**
   * <code>string message_id = 1;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public java.lang.String getMessageId() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageId_ = s;
      return s;
    }
  }
  /**
   * <code>string message_id = 1;</code>
   * @return The bytes for messageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageIdBytes() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STAGE_EXECUTION_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stageExecutionId_ = "";
  /**
   * <code>string stage_execution_id = 2;</code>
   * @return The stageExecutionId.
   */
  @java.lang.Override
  public java.lang.String getStageExecutionId() {
    java.lang.Object ref = stageExecutionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stageExecutionId_ = s;
      return s;
    }
  }
  /**
   * <code>string stage_execution_id = 2;</code>
   * @return The bytes for stageExecutionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStageExecutionIdBytes() {
    java.lang.Object ref = stageExecutionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stageExecutionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATOR_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object operatorId_ = "";
  /**
   * <code>string operator_id = 3;</code>
   * @return The operatorId.
   */
  @java.lang.Override
  public java.lang.String getOperatorId() {
    java.lang.Object ref = operatorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      operatorId_ = s;
      return s;
    }
  }
  /**
   * <code>string operator_id = 3;</code>
   * @return The bytes for operatorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOperatorIdBytes() {
    java.lang.Object ref = operatorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      operatorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROTOCOL_FIELD_NUMBER = 4;
  private int protocol_ = 0;
  /**
   * <code>.mpp.common.v1.Protocol protocol = 4;</code>
   * @return The enum numeric value on the wire for protocol.
   */
  @java.lang.Override public int getProtocolValue() {
    return protocol_;
  }
  /**
   * <code>.mpp.common.v1.Protocol protocol = 4;</code>
   * @return The protocol.
   */
  @java.lang.Override public uz.mpp.platformcontracts.common.v1.Protocol getProtocol() {
    uz.mpp.platformcontracts.common.v1.Protocol result = uz.mpp.platformcontracts.common.v1.Protocol.forNumber(protocol_);
    return result == null ? uz.mpp.platformcontracts.common.v1.Protocol.UNRECOGNIZED : result;
  }

  public static final int SMSC_MESSAGE_ID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object smscMessageId_ = "";
  /**
   * <pre>
   * Идентификатор сообщения на стороне SMSC/оператора, если доступен
   * сразу (не все операторы возвращают его синхронно).
   * </pre>
   *
   * <code>string smsc_message_id = 5;</code>
   * @return The smscMessageId.
   */
  @java.lang.Override
  public java.lang.String getSmscMessageId() {
    java.lang.Object ref = smscMessageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      smscMessageId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Идентификатор сообщения на стороне SMSC/оператора, если доступен
   * сразу (не все операторы возвращают его синхронно).
   * </pre>
   *
   * <code>string smsc_message_id = 5;</code>
   * @return The bytes for smscMessageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSmscMessageIdBytes() {
    java.lang.Object ref = smscMessageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      smscMessageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEGMENT_ID_FIELD_NUMBER = 6;
  private int segmentId_ = 0;
  /**
   * <code>int32 segment_id = 6;</code>
   * @return The segmentId.
   */
  @java.lang.Override
  public int getSegmentId() {
    return segmentId_;
  }

  public static final int SUBMITTED_AT_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp submittedAt_;
  /**
   * <code>.google.protobuf.Timestamp submitted_at = 7;</code>
   * @return Whether the submittedAt field is set.
   */
  @java.lang.Override
  public boolean hasSubmittedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp submitted_at = 7;</code>
   * @return The submittedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getSubmittedAt() {
    return submittedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : submittedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp submitted_at = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getSubmittedAtOrBuilder() {
    return submittedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : submittedAt_;
  }

  public static final int CORRELATION_EXPIRES_AT_FIELD_NUMBER = 8;
  private com.google.protobuf.Timestamp correlationExpiresAt_;
  /**
   * <pre>
   * DLR SLA конкретного оператора — используется для расчёта
   * expires_at в dlr_correlation (data_infrastructure_spec.md §1.8, §1.9a).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp correlation_expires_at = 8;</code>
   * @return Whether the correlationExpiresAt field is set.
   */
  @java.lang.Override
  public boolean hasCorrelationExpiresAt() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * DLR SLA конкретного оператора — используется для расчёта
   * expires_at в dlr_correlation (data_infrastructure_spec.md §1.8, §1.9a).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp correlation_expires_at = 8;</code>
   * @return The correlationExpiresAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCorrelationExpiresAt() {
    return correlationExpiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : correlationExpiresAt_;
  }
  /**
   * <pre>
   * DLR SLA конкретного оператора — используется для расчёта
   * expires_at в dlr_correlation (data_infrastructure_spec.md §1.8, §1.9a).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp correlation_expires_at = 8;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCorrelationExpiresAtOrBuilder() {
    return correlationExpiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : correlationExpiresAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, messageId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stageExecutionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, stageExecutionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(operatorId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, operatorId_);
    }
    if (protocol_ != uz.mpp.platformcontracts.common.v1.Protocol.PROTOCOL_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, protocol_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(smscMessageId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, smscMessageId_);
    }
    if (segmentId_ != 0) {
      output.writeInt32(6, segmentId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(7, getSubmittedAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(8, getCorrelationExpiresAt());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, messageId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stageExecutionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, stageExecutionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(operatorId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, operatorId_);
    }
    if (protocol_ != uz.mpp.platformcontracts.common.v1.Protocol.PROTOCOL_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, protocol_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(smscMessageId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, smscMessageId_);
    }
    if (segmentId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, segmentId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getSubmittedAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getCorrelationExpiresAt());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted)) {
      return super.equals(obj);
    }
    uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted other = (uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted) obj;

    if (!getMessageId()
        .equals(other.getMessageId())) return false;
    if (!getStageExecutionId()
        .equals(other.getStageExecutionId())) return false;
    if (!getOperatorId()
        .equals(other.getOperatorId())) return false;
    if (protocol_ != other.protocol_) return false;
    if (!getSmscMessageId()
        .equals(other.getSmscMessageId())) return false;
    if (getSegmentId()
        != other.getSegmentId()) return false;
    if (hasSubmittedAt() != other.hasSubmittedAt()) return false;
    if (hasSubmittedAt()) {
      if (!getSubmittedAt()
          .equals(other.getSubmittedAt())) return false;
    }
    if (hasCorrelationExpiresAt() != other.hasCorrelationExpiresAt()) return false;
    if (hasCorrelationExpiresAt()) {
      if (!getCorrelationExpiresAt()
          .equals(other.getCorrelationExpiresAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMessageId().hashCode();
    hash = (37 * hash) + STAGE_EXECUTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getStageExecutionId().hashCode();
    hash = (37 * hash) + OPERATOR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOperatorId().hashCode();
    hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
    hash = (53 * hash) + protocol_;
    hash = (37 * hash) + SMSC_MESSAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSmscMessageId().hashCode();
    hash = (37 * hash) + SEGMENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSegmentId();
    if (hasSubmittedAt()) {
      hash = (37 * hash) + SUBMITTED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getSubmittedAt().hashCode();
    }
    if (hasCorrelationExpiresAt()) {
      hash = (37 * hash) + CORRELATION_EXPIRES_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCorrelationExpiresAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Принятый submit — публикуется в operator.submit.accepted как Operator SMPP
   * Session Manager, так и Operator HTTP Gateway в один и тот же формат;
   * downstream (DLR Correlation Writer, Delivery Reconciliation) не различает
   * протокол (HLD §11.3, data_infrastructure_spec.md §3).
   * </pre>
   *
   * Protobuf type {@code mpp.events.v1.OperatorSubmitAccepted}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mpp.events.v1.OperatorSubmitAccepted)
      uz.mpp.platformcontracts.events.v1.OperatorSubmitAcceptedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uz.mpp.platformcontracts.events.v1.OperatorEvents.internal_static_mpp_events_v1_OperatorSubmitAccepted_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uz.mpp.platformcontracts.events.v1.OperatorEvents.internal_static_mpp_events_v1_OperatorSubmitAccepted_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted.class, uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted.Builder.class);
    }

    // Construct using uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetSubmittedAtFieldBuilder();
        internalGetCorrelationExpiresAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      messageId_ = "";
      stageExecutionId_ = "";
      operatorId_ = "";
      protocol_ = 0;
      smscMessageId_ = "";
      segmentId_ = 0;
      submittedAt_ = null;
      if (submittedAtBuilder_ != null) {
        submittedAtBuilder_.dispose();
        submittedAtBuilder_ = null;
      }
      correlationExpiresAt_ = null;
      if (correlationExpiresAtBuilder_ != null) {
        correlationExpiresAtBuilder_.dispose();
        correlationExpiresAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uz.mpp.platformcontracts.events.v1.OperatorEvents.internal_static_mpp_events_v1_OperatorSubmitAccepted_descriptor;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted getDefaultInstanceForType() {
      return uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted.getDefaultInstance();
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted build() {
      uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted buildPartial() {
      uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted result = new uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.messageId_ = messageId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.stageExecutionId_ = stageExecutionId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.operatorId_ = operatorId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.protocol_ = protocol_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.smscMessageId_ = smscMessageId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.segmentId_ = segmentId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.submittedAt_ = submittedAtBuilder_ == null
            ? submittedAt_
            : submittedAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.correlationExpiresAt_ = correlationExpiresAtBuilder_ == null
            ? correlationExpiresAt_
            : correlationExpiresAtBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted) {
        return mergeFrom((uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted other) {
      if (other == uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted.getDefaultInstance()) return this;
      if (!other.getMessageId().isEmpty()) {
        messageId_ = other.messageId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getStageExecutionId().isEmpty()) {
        stageExecutionId_ = other.stageExecutionId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getOperatorId().isEmpty()) {
        operatorId_ = other.operatorId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.protocol_ != 0) {
        setProtocolValue(other.getProtocolValue());
      }
      if (!other.getSmscMessageId().isEmpty()) {
        smscMessageId_ = other.smscMessageId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getSegmentId() != 0) {
        setSegmentId(other.getSegmentId());
      }
      if (other.hasSubmittedAt()) {
        mergeSubmittedAt(other.getSubmittedAt());
      }
      if (other.hasCorrelationExpiresAt()) {
        mergeCorrelationExpiresAt(other.getCorrelationExpiresAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              messageId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              stageExecutionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              operatorId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              protocol_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              smscMessageId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              segmentId_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              input.readMessage(
                  internalGetSubmittedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  internalGetCorrelationExpiresAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object messageId_ = "";
    /**
     * <code>string message_id = 1;</code>
     * @return The messageId.
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message_id = 1;</code>
     * @return The bytes for messageId.
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message_id = 1;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      messageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string message_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      messageId_ = getDefaultInstance().getMessageId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string message_id = 1;</code>
     * @param value The bytes for messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      messageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object stageExecutionId_ = "";
    /**
     * <code>string stage_execution_id = 2;</code>
     * @return The stageExecutionId.
     */
    public java.lang.String getStageExecutionId() {
      java.lang.Object ref = stageExecutionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stageExecutionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stage_execution_id = 2;</code>
     * @return The bytes for stageExecutionId.
     */
    public com.google.protobuf.ByteString
        getStageExecutionIdBytes() {
      java.lang.Object ref = stageExecutionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stageExecutionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stage_execution_id = 2;</code>
     * @param value The stageExecutionId to set.
     * @return This builder for chaining.
     */
    public Builder setStageExecutionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stageExecutionId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string stage_execution_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStageExecutionId() {
      stageExecutionId_ = getDefaultInstance().getStageExecutionId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string stage_execution_id = 2;</code>
     * @param value The bytes for stageExecutionId to set.
     * @return This builder for chaining.
     */
    public Builder setStageExecutionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stageExecutionId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object operatorId_ = "";
    /**
     * <code>string operator_id = 3;</code>
     * @return The operatorId.
     */
    public java.lang.String getOperatorId() {
      java.lang.Object ref = operatorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operatorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string operator_id = 3;</code>
     * @return The bytes for operatorId.
     */
    public com.google.protobuf.ByteString
        getOperatorIdBytes() {
      java.lang.Object ref = operatorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operatorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string operator_id = 3;</code>
     * @param value The operatorId to set.
     * @return This builder for chaining.
     */
    public Builder setOperatorId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      operatorId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string operator_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperatorId() {
      operatorId_ = getDefaultInstance().getOperatorId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string operator_id = 3;</code>
     * @param value The bytes for operatorId to set.
     * @return This builder for chaining.
     */
    public Builder setOperatorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      operatorId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int protocol_ = 0;
    /**
     * <code>.mpp.common.v1.Protocol protocol = 4;</code>
     * @return The enum numeric value on the wire for protocol.
     */
    @java.lang.Override public int getProtocolValue() {
      return protocol_;
    }
    /**
     * <code>.mpp.common.v1.Protocol protocol = 4;</code>
     * @param value The enum numeric value on the wire for protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolValue(int value) {
      protocol_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.mpp.common.v1.Protocol protocol = 4;</code>
     * @return The protocol.
     */
    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.Protocol getProtocol() {
      uz.mpp.platformcontracts.common.v1.Protocol result = uz.mpp.platformcontracts.common.v1.Protocol.forNumber(protocol_);
      return result == null ? uz.mpp.platformcontracts.common.v1.Protocol.UNRECOGNIZED : result;
    }
    /**
     * <code>.mpp.common.v1.Protocol protocol = 4;</code>
     * @param value The protocol to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setProtocol(uz.mpp.platformcontracts.common.v1.Protocol value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000008;
      protocol_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.mpp.common.v1.Protocol protocol = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocol() {
      bitField0_ = (bitField0_ & ~0x00000008);
      protocol_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object smscMessageId_ = "";
    /**
     * <pre>
     * Идентификатор сообщения на стороне SMSC/оператора, если доступен
     * сразу (не все операторы возвращают его синхронно).
     * </pre>
     *
     * <code>string smsc_message_id = 5;</code>
     * @return The smscMessageId.
     */
    public java.lang.String getSmscMessageId() {
      java.lang.Object ref = smscMessageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        smscMessageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор сообщения на стороне SMSC/оператора, если доступен
     * сразу (не все операторы возвращают его синхронно).
     * </pre>
     *
     * <code>string smsc_message_id = 5;</code>
     * @return The bytes for smscMessageId.
     */
    public com.google.protobuf.ByteString
        getSmscMessageIdBytes() {
      java.lang.Object ref = smscMessageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        smscMessageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор сообщения на стороне SMSC/оператора, если доступен
     * сразу (не все операторы возвращают его синхронно).
     * </pre>
     *
     * <code>string smsc_message_id = 5;</code>
     * @param value The smscMessageId to set.
     * @return This builder for chaining.
     */
    public Builder setSmscMessageId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      smscMessageId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор сообщения на стороне SMSC/оператора, если доступен
     * сразу (не все операторы возвращают его синхронно).
     * </pre>
     *
     * <code>string smsc_message_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSmscMessageId() {
      smscMessageId_ = getDefaultInstance().getSmscMessageId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор сообщения на стороне SMSC/оператора, если доступен
     * сразу (не все операторы возвращают его синхронно).
     * </pre>
     *
     * <code>string smsc_message_id = 5;</code>
     * @param value The bytes for smscMessageId to set.
     * @return This builder for chaining.
     */
    public Builder setSmscMessageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      smscMessageId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int segmentId_ ;
    /**
     * <code>int32 segment_id = 6;</code>
     * @return The segmentId.
     */
    @java.lang.Override
    public int getSegmentId() {
      return segmentId_;
    }
    /**
     * <code>int32 segment_id = 6;</code>
     * @param value The segmentId to set.
     * @return This builder for chaining.
     */
    public Builder setSegmentId(int value) {

      segmentId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 segment_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSegmentId() {
      bitField0_ = (bitField0_ & ~0x00000020);
      segmentId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp submittedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> submittedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 7;</code>
     * @return Whether the submittedAt field is set.
     */
    public boolean hasSubmittedAt() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 7;</code>
     * @return The submittedAt.
     */
    public com.google.protobuf.Timestamp getSubmittedAt() {
      if (submittedAtBuilder_ == null) {
        return submittedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : submittedAt_;
      } else {
        return submittedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 7;</code>
     */
    public Builder setSubmittedAt(com.google.protobuf.Timestamp value) {
      if (submittedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        submittedAt_ = value;
      } else {
        submittedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 7;</code>
     */
    public Builder setSubmittedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (submittedAtBuilder_ == null) {
        submittedAt_ = builderForValue.build();
      } else {
        submittedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 7;</code>
     */
    public Builder mergeSubmittedAt(com.google.protobuf.Timestamp value) {
      if (submittedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          submittedAt_ != null &&
          submittedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getSubmittedAtBuilder().mergeFrom(value);
        } else {
          submittedAt_ = value;
        }
      } else {
        submittedAtBuilder_.mergeFrom(value);
      }
      if (submittedAt_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 7;</code>
     */
    public Builder clearSubmittedAt() {
      bitField0_ = (bitField0_ & ~0x00000040);
      submittedAt_ = null;
      if (submittedAtBuilder_ != null) {
        submittedAtBuilder_.dispose();
        submittedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder getSubmittedAtBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return internalGetSubmittedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getSubmittedAtOrBuilder() {
      if (submittedAtBuilder_ != null) {
        return submittedAtBuilder_.getMessageOrBuilder();
      } else {
        return submittedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : submittedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetSubmittedAtFieldBuilder() {
      if (submittedAtBuilder_ == null) {
        submittedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getSubmittedAt(),
                getParentForChildren(),
                isClean());
        submittedAt_ = null;
      }
      return submittedAtBuilder_;
    }

    private com.google.protobuf.Timestamp correlationExpiresAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> correlationExpiresAtBuilder_;
    /**
     * <pre>
     * DLR SLA конкретного оператора — используется для расчёта
     * expires_at в dlr_correlation (data_infrastructure_spec.md §1.8, §1.9a).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp correlation_expires_at = 8;</code>
     * @return Whether the correlationExpiresAt field is set.
     */
    public boolean hasCorrelationExpiresAt() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * DLR SLA конкретного оператора — используется для расчёта
     * expires_at в dlr_correlation (data_infrastructure_spec.md §1.8, §1.9a).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp correlation_expires_at = 8;</code>
     * @return The correlationExpiresAt.
     */
    public com.google.protobuf.Timestamp getCorrelationExpiresAt() {
      if (correlationExpiresAtBuilder_ == null) {
        return correlationExpiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : correlationExpiresAt_;
      } else {
        return correlationExpiresAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * DLR SLA конкретного оператора — используется для расчёта
     * expires_at в dlr_correlation (data_infrastructure_spec.md §1.8, §1.9a).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp correlation_expires_at = 8;</code>
     */
    public Builder setCorrelationExpiresAt(com.google.protobuf.Timestamp value) {
      if (correlationExpiresAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        correlationExpiresAt_ = value;
      } else {
        correlationExpiresAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * DLR SLA конкретного оператора — используется для расчёта
     * expires_at в dlr_correlation (data_infrastructure_spec.md §1.8, §1.9a).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp correlation_expires_at = 8;</code>
     */
    public Builder setCorrelationExpiresAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (correlationExpiresAtBuilder_ == null) {
        correlationExpiresAt_ = builderForValue.build();
      } else {
        correlationExpiresAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * DLR SLA конкретного оператора — используется для расчёта
     * expires_at в dlr_correlation (data_infrastructure_spec.md §1.8, §1.9a).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp correlation_expires_at = 8;</code>
     */
    public Builder mergeCorrelationExpiresAt(com.google.protobuf.Timestamp value) {
      if (correlationExpiresAtBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          correlationExpiresAt_ != null &&
          correlationExpiresAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCorrelationExpiresAtBuilder().mergeFrom(value);
        } else {
          correlationExpiresAt_ = value;
        }
      } else {
        correlationExpiresAtBuilder_.mergeFrom(value);
      }
      if (correlationExpiresAt_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * DLR SLA конкретного оператора — используется для расчёта
     * expires_at в dlr_correlation (data_infrastructure_spec.md §1.8, §1.9a).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp correlation_expires_at = 8;</code>
     */
    public Builder clearCorrelationExpiresAt() {
      bitField0_ = (bitField0_ & ~0x00000080);
      correlationExpiresAt_ = null;
      if (correlationExpiresAtBuilder_ != null) {
        correlationExpiresAtBuilder_.dispose();
        correlationExpiresAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * DLR SLA конкретного оператора — используется для расчёта
     * expires_at в dlr_correlation (data_infrastructure_spec.md §1.8, §1.9a).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp correlation_expires_at = 8;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCorrelationExpiresAtBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return internalGetCorrelationExpiresAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * DLR SLA конкретного оператора — используется для расчёта
     * expires_at в dlr_correlation (data_infrastructure_spec.md §1.8, §1.9a).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp correlation_expires_at = 8;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCorrelationExpiresAtOrBuilder() {
      if (correlationExpiresAtBuilder_ != null) {
        return correlationExpiresAtBuilder_.getMessageOrBuilder();
      } else {
        return correlationExpiresAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : correlationExpiresAt_;
      }
    }
    /**
     * <pre>
     * DLR SLA конкретного оператора — используется для расчёта
     * expires_at в dlr_correlation (data_infrastructure_spec.md §1.8, §1.9a).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp correlation_expires_at = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetCorrelationExpiresAtFieldBuilder() {
      if (correlationExpiresAtBuilder_ == null) {
        correlationExpiresAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCorrelationExpiresAt(),
                getParentForChildren(),
                isClean());
        correlationExpiresAt_ = null;
      }
      return correlationExpiresAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:mpp.events.v1.OperatorSubmitAccepted)
  }

  // @@protoc_insertion_point(class_scope:mpp.events.v1.OperatorSubmitAccepted)
  private static final uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted();
  }

  public static uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OperatorSubmitAccepted>
      PARSER = new com.google.protobuf.AbstractParser<OperatorSubmitAccepted>() {
    @java.lang.Override
    public OperatorSubmitAccepted parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OperatorSubmitAccepted> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OperatorSubmitAccepted> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uz.mpp.platformcontracts.events.v1.OperatorSubmitAccepted getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

