// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/scheduler_events.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.events.v1;

@com.google.protobuf.Generated
public interface SchedulerHoldCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.events.v1.SchedulerHoldCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message_id = 1;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <code>string message_id = 1;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>string stage_execution_id = 2;</code>
   * @return The stageExecutionId.
   */
  java.lang.String getStageExecutionId();
  /**
   * <code>string stage_execution_id = 2;</code>
   * @return The bytes for stageExecutionId.
   */
  com.google.protobuf.ByteString
      getStageExecutionIdBytes();

  /**
   * <code>.mpp.common.v1.ExecutionControlScope scope = 3;</code>
   * @return The enum numeric value on the wire for scope.
   */
  int getScopeValue();
  /**
   * <code>.mpp.common.v1.ExecutionControlScope scope = 3;</code>
   * @return The scope.
   */
  uz.mpp.platformcontracts.common.v1.ExecutionControlScope getScope();

  /**
   * <code>string scope_id = 4;</code>
   * @return The scopeId.
   */
  java.lang.String getScopeId();
  /**
   * <code>string scope_id = 4;</code>
   * @return The bytes for scopeId.
   */
  com.google.protobuf.ByteString
      getScopeIdBytes();

  /**
   * <code>.mpp.common.v1.StageName stage_name = 5;</code>
   * @return The enum numeric value on the wire for stageName.
   */
  int getStageNameValue();
  /**
   * <code>.mpp.common.v1.StageName stage_name = 5;</code>
   * @return The stageName.
   */
  uz.mpp.platformcontracts.common.v1.StageName getStageName();

  /**
   * <code>.google.protobuf.Timestamp held_at = 6;</code>
   * @return Whether the heldAt field is set.
   */
  boolean hasHeldAt();
  /**
   * <code>.google.protobuf.Timestamp held_at = 6;</code>
   * @return The heldAt.
   */
  com.google.protobuf.Timestamp getHeldAt();
  /**
   * <code>.google.protobuf.Timestamp held_at = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getHeldAtOrBuilder();
}
