// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/scheduler_events.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.events.v1;

/**
 * <pre>
 * Задача Background Lane в scheduler.background.commands (HLD §9.3, §14, §19).
 * </pre>
 *
 * Protobuf type {@code mpp.events.v1.SchedulerBackgroundTask}
 */
@com.google.protobuf.Generated
public final class SchedulerBackgroundTask extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:mpp.events.v1.SchedulerBackgroundTask)
    SchedulerBackgroundTaskOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "SchedulerBackgroundTask");
  }
  // Use SchedulerBackgroundTask.newBuilder() to construct.
  private SchedulerBackgroundTask(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SchedulerBackgroundTask() {
    taskType_ = 0;
    sourceEventId_ = "";
    targetTopic_ = "";
    messageId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uz.mpp.platformcontracts.events.v1.SchedulerEvents.internal_static_mpp_events_v1_SchedulerBackgroundTask_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return uz.mpp.platformcontracts.events.v1.SchedulerEvents.internal_static_mpp_events_v1_SchedulerBackgroundTask_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uz.mpp.platformcontracts.events.v1.SchedulerEvents.internal_static_mpp_events_v1_SchedulerBackgroundTask_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask.class, uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask.Builder.class);
  }

  private int bitField0_;
  public static final int TASK_TYPE_FIELD_NUMBER = 1;
  private int taskType_ = 0;
  /**
   * <code>.mpp.common.v1.BackgroundTaskType task_type = 1;</code>
   * @return The enum numeric value on the wire for taskType.
   */
  @java.lang.Override public int getTaskTypeValue() {
    return taskType_;
  }
  /**
   * <code>.mpp.common.v1.BackgroundTaskType task_type = 1;</code>
   * @return The taskType.
   */
  @java.lang.Override public uz.mpp.platformcontracts.common.v1.BackgroundTaskType getTaskType() {
    uz.mpp.platformcontracts.common.v1.BackgroundTaskType result = uz.mpp.platformcontracts.common.v1.BackgroundTaskType.forNumber(taskType_);
    return result == null ? uz.mpp.platformcontracts.common.v1.BackgroundTaskType.UNRECOGNIZED : result;
  }

  public static final int SOURCE_EVENT_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceEventId_ = "";
  /**
   * <pre>
   * Для DLR_CORRELATION_RETRY — event_id исходного operator.dlr;
   * для NOTIFICATION_RETRY — event_id исходного message.lifecycle.
   * </pre>
   *
   * <code>string source_event_id = 2;</code>
   * @return The sourceEventId.
   */
  @java.lang.Override
  public java.lang.String getSourceEventId() {
    java.lang.Object ref = sourceEventId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceEventId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Для DLR_CORRELATION_RETRY — event_id исходного operator.dlr;
   * для NOTIFICATION_RETRY — event_id исходного message.lifecycle.
   * </pre>
   *
   * <code>string source_event_id = 2;</code>
   * @return The bytes for sourceEventId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceEventIdBytes() {
    java.lang.Object ref = sourceEventId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceEventId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTEMPT_FIELD_NUMBER = 3;
  private int attempt_ = 0;
  /**
   * <code>int32 attempt = 3;</code>
   * @return The attempt.
   */
  @java.lang.Override
  public int getAttempt() {
    return attempt_;
  }

  public static final int DUE_AT_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp dueAt_;
  /**
   * <code>.google.protobuf.Timestamp due_at = 4;</code>
   * @return Whether the dueAt field is set.
   */
  @java.lang.Override
  public boolean hasDueAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp due_at = 4;</code>
   * @return The dueAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDueAt() {
    return dueAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dueAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp due_at = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getDueAtOrBuilder() {
    return dueAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dueAt_;
  }

  public static final int DEADLINE_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp deadline_;
  /**
   * <code>.google.protobuf.Timestamp deadline = 5;</code>
   * @return Whether the deadline field is set.
   */
  @java.lang.Override
  public boolean hasDeadline() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp deadline = 5;</code>
   * @return The deadline.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDeadline() {
    return deadline_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deadline_;
  }
  /**
   * <code>.google.protobuf.Timestamp deadline = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getDeadlineOrBuilder() {
    return deadline_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deadline_;
  }

  public static final int TARGET_TOPIC_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object targetTopic_ = "";
  /**
   * <pre>
   * Разрешённый список: "operator.dlr.unresolved" | "notification.retry" |
   * "pipeline.retry.triggers" — не произвольная строка (HLD §14, защита от
   * использования Scheduler как открытого редиректа внутри Kafka).
   * </pre>
   *
   * <code>string target_topic = 6;</code>
   * @return The targetTopic.
   */
  @java.lang.Override
  public java.lang.String getTargetTopic() {
    java.lang.Object ref = targetTopic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetTopic_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Разрешённый список: "operator.dlr.unresolved" | "notification.retry" |
   * "pipeline.retry.triggers" — не произвольная строка (HLD §14, защита от
   * использования Scheduler как открытого редиректа внутри Kafka).
   * </pre>
   *
   * <code>string target_topic = 6;</code>
   * @return The bytes for targetTopic.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTargetTopicBytes() {
    java.lang.Object ref = targetTopic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetTopic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_ID_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object messageId_ = "";
  /**
   * <pre>
   * Только для BACKGROUND_TASK_TYPE_STAGE_RETRY — `source_event_id` там не
   * подходит по смыслу (для остальных двух типов это event_id ЧУЖОГО
   * события-источника, здесь же нужен именно message_id самого Pipeline
   * Engine, чтобы найти ExecutionState в Runtime Redis при редиспатче).
   * </pre>
   *
   * <code>string message_id = 7;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public java.lang.String getMessageId() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Только для BACKGROUND_TASK_TYPE_STAGE_RETRY — `source_event_id` там не
   * подходит по смыслу (для остальных двух типов это event_id ЧУЖОГО
   * события-источника, здесь же нужен именно message_id самого Pipeline
   * Engine, чтобы найти ExecutionState в Runtime Redis при редиспатче).
   * </pre>
   *
   * <code>string message_id = 7;</code>
   * @return The bytes for messageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageIdBytes() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (taskType_ != uz.mpp.platformcontracts.common.v1.BackgroundTaskType.BACKGROUND_TASK_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, taskType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceEventId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, sourceEventId_);
    }
    if (attempt_ != 0) {
      output.writeInt32(3, attempt_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getDueAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(5, getDeadline());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetTopic_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, targetTopic_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, messageId_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (taskType_ != uz.mpp.platformcontracts.common.v1.BackgroundTaskType.BACKGROUND_TASK_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, taskType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceEventId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, sourceEventId_);
    }
    if (attempt_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, attempt_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDueAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDeadline());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetTopic_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, targetTopic_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, messageId_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask)) {
      return super.equals(obj);
    }
    uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask other = (uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask) obj;

    if (taskType_ != other.taskType_) return false;
    if (!getSourceEventId()
        .equals(other.getSourceEventId())) return false;
    if (getAttempt()
        != other.getAttempt()) return false;
    if (hasDueAt() != other.hasDueAt()) return false;
    if (hasDueAt()) {
      if (!getDueAt()
          .equals(other.getDueAt())) return false;
    }
    if (hasDeadline() != other.hasDeadline()) return false;
    if (hasDeadline()) {
      if (!getDeadline()
          .equals(other.getDeadline())) return false;
    }
    if (!getTargetTopic()
        .equals(other.getTargetTopic())) return false;
    if (!getMessageId()
        .equals(other.getMessageId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TASK_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + taskType_;
    hash = (37 * hash) + SOURCE_EVENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSourceEventId().hashCode();
    hash = (37 * hash) + ATTEMPT_FIELD_NUMBER;
    hash = (53 * hash) + getAttempt();
    if (hasDueAt()) {
      hash = (37 * hash) + DUE_AT_FIELD_NUMBER;
      hash = (53 * hash) + getDueAt().hashCode();
    }
    if (hasDeadline()) {
      hash = (37 * hash) + DEADLINE_FIELD_NUMBER;
      hash = (53 * hash) + getDeadline().hashCode();
    }
    hash = (37 * hash) + TARGET_TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getTargetTopic().hashCode();
    hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMessageId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Задача Background Lane в scheduler.background.commands (HLD §9.3, §14, §19).
   * </pre>
   *
   * Protobuf type {@code mpp.events.v1.SchedulerBackgroundTask}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mpp.events.v1.SchedulerBackgroundTask)
      uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTaskOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uz.mpp.platformcontracts.events.v1.SchedulerEvents.internal_static_mpp_events_v1_SchedulerBackgroundTask_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uz.mpp.platformcontracts.events.v1.SchedulerEvents.internal_static_mpp_events_v1_SchedulerBackgroundTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask.class, uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask.Builder.class);
    }

    // Construct using uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetDueAtFieldBuilder();
        internalGetDeadlineFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      taskType_ = 0;
      sourceEventId_ = "";
      attempt_ = 0;
      dueAt_ = null;
      if (dueAtBuilder_ != null) {
        dueAtBuilder_.dispose();
        dueAtBuilder_ = null;
      }
      deadline_ = null;
      if (deadlineBuilder_ != null) {
        deadlineBuilder_.dispose();
        deadlineBuilder_ = null;
      }
      targetTopic_ = "";
      messageId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uz.mpp.platformcontracts.events.v1.SchedulerEvents.internal_static_mpp_events_v1_SchedulerBackgroundTask_descriptor;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask getDefaultInstanceForType() {
      return uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask.getDefaultInstance();
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask build() {
      uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask buildPartial() {
      uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask result = new uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.taskType_ = taskType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sourceEventId_ = sourceEventId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.attempt_ = attempt_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.dueAt_ = dueAtBuilder_ == null
            ? dueAt_
            : dueAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.deadline_ = deadlineBuilder_ == null
            ? deadline_
            : deadlineBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.targetTopic_ = targetTopic_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.messageId_ = messageId_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask) {
        return mergeFrom((uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask other) {
      if (other == uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask.getDefaultInstance()) return this;
      if (other.taskType_ != 0) {
        setTaskTypeValue(other.getTaskTypeValue());
      }
      if (!other.getSourceEventId().isEmpty()) {
        sourceEventId_ = other.sourceEventId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getAttempt() != 0) {
        setAttempt(other.getAttempt());
      }
      if (other.hasDueAt()) {
        mergeDueAt(other.getDueAt());
      }
      if (other.hasDeadline()) {
        mergeDeadline(other.getDeadline());
      }
      if (!other.getTargetTopic().isEmpty()) {
        targetTopic_ = other.targetTopic_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getMessageId().isEmpty()) {
        messageId_ = other.messageId_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              taskType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              sourceEventId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              attempt_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  internalGetDueAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetDeadlineFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              targetTopic_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              messageId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int taskType_ = 0;
    /**
     * <code>.mpp.common.v1.BackgroundTaskType task_type = 1;</code>
     * @return The enum numeric value on the wire for taskType.
     */
    @java.lang.Override public int getTaskTypeValue() {
      return taskType_;
    }
    /**
     * <code>.mpp.common.v1.BackgroundTaskType task_type = 1;</code>
     * @param value The enum numeric value on the wire for taskType to set.
     * @return This builder for chaining.
     */
    public Builder setTaskTypeValue(int value) {
      taskType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mpp.common.v1.BackgroundTaskType task_type = 1;</code>
     * @return The taskType.
     */
    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.BackgroundTaskType getTaskType() {
      uz.mpp.platformcontracts.common.v1.BackgroundTaskType result = uz.mpp.platformcontracts.common.v1.BackgroundTaskType.forNumber(taskType_);
      return result == null ? uz.mpp.platformcontracts.common.v1.BackgroundTaskType.UNRECOGNIZED : result;
    }
    /**
     * <code>.mpp.common.v1.BackgroundTaskType task_type = 1;</code>
     * @param value The taskType to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setTaskType(uz.mpp.platformcontracts.common.v1.BackgroundTaskType value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      taskType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.mpp.common.v1.BackgroundTaskType task_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      taskType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object sourceEventId_ = "";
    /**
     * <pre>
     * Для DLR_CORRELATION_RETRY — event_id исходного operator.dlr;
     * для NOTIFICATION_RETRY — event_id исходного message.lifecycle.
     * </pre>
     *
     * <code>string source_event_id = 2;</code>
     * @return The sourceEventId.
     */
    public java.lang.String getSourceEventId() {
      java.lang.Object ref = sourceEventId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceEventId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Для DLR_CORRELATION_RETRY — event_id исходного operator.dlr;
     * для NOTIFICATION_RETRY — event_id исходного message.lifecycle.
     * </pre>
     *
     * <code>string source_event_id = 2;</code>
     * @return The bytes for sourceEventId.
     */
    public com.google.protobuf.ByteString
        getSourceEventIdBytes() {
      java.lang.Object ref = sourceEventId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceEventId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Для DLR_CORRELATION_RETRY — event_id исходного operator.dlr;
     * для NOTIFICATION_RETRY — event_id исходного message.lifecycle.
     * </pre>
     *
     * <code>string source_event_id = 2;</code>
     * @param value The sourceEventId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceEventId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceEventId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Для DLR_CORRELATION_RETRY — event_id исходного operator.dlr;
     * для NOTIFICATION_RETRY — event_id исходного message.lifecycle.
     * </pre>
     *
     * <code>string source_event_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceEventId() {
      sourceEventId_ = getDefaultInstance().getSourceEventId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Для DLR_CORRELATION_RETRY — event_id исходного operator.dlr;
     * для NOTIFICATION_RETRY — event_id исходного message.lifecycle.
     * </pre>
     *
     * <code>string source_event_id = 2;</code>
     * @param value The bytes for sourceEventId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceEventIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceEventId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int attempt_ ;
    /**
     * <code>int32 attempt = 3;</code>
     * @return The attempt.
     */
    @java.lang.Override
    public int getAttempt() {
      return attempt_;
    }
    /**
     * <code>int32 attempt = 3;</code>
     * @param value The attempt to set.
     * @return This builder for chaining.
     */
    public Builder setAttempt(int value) {

      attempt_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 attempt = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAttempt() {
      bitField0_ = (bitField0_ & ~0x00000004);
      attempt_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp dueAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dueAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp due_at = 4;</code>
     * @return Whether the dueAt field is set.
     */
    public boolean hasDueAt() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp due_at = 4;</code>
     * @return The dueAt.
     */
    public com.google.protobuf.Timestamp getDueAt() {
      if (dueAtBuilder_ == null) {
        return dueAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dueAt_;
      } else {
        return dueAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp due_at = 4;</code>
     */
    public Builder setDueAt(com.google.protobuf.Timestamp value) {
      if (dueAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dueAt_ = value;
      } else {
        dueAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp due_at = 4;</code>
     */
    public Builder setDueAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dueAtBuilder_ == null) {
        dueAt_ = builderForValue.build();
      } else {
        dueAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp due_at = 4;</code>
     */
    public Builder mergeDueAt(com.google.protobuf.Timestamp value) {
      if (dueAtBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          dueAt_ != null &&
          dueAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getDueAtBuilder().mergeFrom(value);
        } else {
          dueAt_ = value;
        }
      } else {
        dueAtBuilder_.mergeFrom(value);
      }
      if (dueAt_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp due_at = 4;</code>
     */
    public Builder clearDueAt() {
      bitField0_ = (bitField0_ & ~0x00000008);
      dueAt_ = null;
      if (dueAtBuilder_ != null) {
        dueAtBuilder_.dispose();
        dueAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp due_at = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDueAtBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetDueAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp due_at = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDueAtOrBuilder() {
      if (dueAtBuilder_ != null) {
        return dueAtBuilder_.getMessageOrBuilder();
      } else {
        return dueAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dueAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp due_at = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetDueAtFieldBuilder() {
      if (dueAtBuilder_ == null) {
        dueAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDueAt(),
                getParentForChildren(),
                isClean());
        dueAt_ = null;
      }
      return dueAtBuilder_;
    }

    private com.google.protobuf.Timestamp deadline_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> deadlineBuilder_;
    /**
     * <code>.google.protobuf.Timestamp deadline = 5;</code>
     * @return Whether the deadline field is set.
     */
    public boolean hasDeadline() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp deadline = 5;</code>
     * @return The deadline.
     */
    public com.google.protobuf.Timestamp getDeadline() {
      if (deadlineBuilder_ == null) {
        return deadline_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deadline_;
      } else {
        return deadlineBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp deadline = 5;</code>
     */
    public Builder setDeadline(com.google.protobuf.Timestamp value) {
      if (deadlineBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deadline_ = value;
      } else {
        deadlineBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp deadline = 5;</code>
     */
    public Builder setDeadline(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (deadlineBuilder_ == null) {
        deadline_ = builderForValue.build();
      } else {
        deadlineBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp deadline = 5;</code>
     */
    public Builder mergeDeadline(com.google.protobuf.Timestamp value) {
      if (deadlineBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          deadline_ != null &&
          deadline_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getDeadlineBuilder().mergeFrom(value);
        } else {
          deadline_ = value;
        }
      } else {
        deadlineBuilder_.mergeFrom(value);
      }
      if (deadline_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp deadline = 5;</code>
     */
    public Builder clearDeadline() {
      bitField0_ = (bitField0_ & ~0x00000010);
      deadline_ = null;
      if (deadlineBuilder_ != null) {
        deadlineBuilder_.dispose();
        deadlineBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp deadline = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDeadlineBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetDeadlineFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp deadline = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDeadlineOrBuilder() {
      if (deadlineBuilder_ != null) {
        return deadlineBuilder_.getMessageOrBuilder();
      } else {
        return deadline_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : deadline_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp deadline = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetDeadlineFieldBuilder() {
      if (deadlineBuilder_ == null) {
        deadlineBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDeadline(),
                getParentForChildren(),
                isClean());
        deadline_ = null;
      }
      return deadlineBuilder_;
    }

    private java.lang.Object targetTopic_ = "";
    /**
     * <pre>
     * Разрешённый список: "operator.dlr.unresolved" | "notification.retry" |
     * "pipeline.retry.triggers" — не произвольная строка (HLD §14, защита от
     * использования Scheduler как открытого редиректа внутри Kafka).
     * </pre>
     *
     * <code>string target_topic = 6;</code>
     * @return The targetTopic.
     */
    public java.lang.String getTargetTopic() {
      java.lang.Object ref = targetTopic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetTopic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Разрешённый список: "operator.dlr.unresolved" | "notification.retry" |
     * "pipeline.retry.triggers" — не произвольная строка (HLD §14, защита от
     * использования Scheduler как открытого редиректа внутри Kafka).
     * </pre>
     *
     * <code>string target_topic = 6;</code>
     * @return The bytes for targetTopic.
     */
    public com.google.protobuf.ByteString
        getTargetTopicBytes() {
      java.lang.Object ref = targetTopic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetTopic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Разрешённый список: "operator.dlr.unresolved" | "notification.retry" |
     * "pipeline.retry.triggers" — не произвольная строка (HLD §14, защита от
     * использования Scheduler как открытого редиректа внутри Kafka).
     * </pre>
     *
     * <code>string target_topic = 6;</code>
     * @param value The targetTopic to set.
     * @return This builder for chaining.
     */
    public Builder setTargetTopic(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      targetTopic_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Разрешённый список: "operator.dlr.unresolved" | "notification.retry" |
     * "pipeline.retry.triggers" — не произвольная строка (HLD §14, защита от
     * использования Scheduler как открытого редиректа внутри Kafka).
     * </pre>
     *
     * <code>string target_topic = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetTopic() {
      targetTopic_ = getDefaultInstance().getTargetTopic();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Разрешённый список: "operator.dlr.unresolved" | "notification.retry" |
     * "pipeline.retry.triggers" — не произвольная строка (HLD §14, защита от
     * использования Scheduler как открытого редиректа внутри Kafka).
     * </pre>
     *
     * <code>string target_topic = 6;</code>
     * @param value The bytes for targetTopic to set.
     * @return This builder for chaining.
     */
    public Builder setTargetTopicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      targetTopic_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object messageId_ = "";
    /**
     * <pre>
     * Только для BACKGROUND_TASK_TYPE_STAGE_RETRY — `source_event_id` там не
     * подходит по смыслу (для остальных двух типов это event_id ЧУЖОГО
     * события-источника, здесь же нужен именно message_id самого Pipeline
     * Engine, чтобы найти ExecutionState в Runtime Redis при редиспатче).
     * </pre>
     *
     * <code>string message_id = 7;</code>
     * @return The messageId.
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Только для BACKGROUND_TASK_TYPE_STAGE_RETRY — `source_event_id` там не
     * подходит по смыслу (для остальных двух типов это event_id ЧУЖОГО
     * события-источника, здесь же нужен именно message_id самого Pipeline
     * Engine, чтобы найти ExecutionState в Runtime Redis при редиспатче).
     * </pre>
     *
     * <code>string message_id = 7;</code>
     * @return The bytes for messageId.
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Только для BACKGROUND_TASK_TYPE_STAGE_RETRY — `source_event_id` там не
     * подходит по смыслу (для остальных двух типов это event_id ЧУЖОГО
     * события-источника, здесь же нужен именно message_id самого Pipeline
     * Engine, чтобы найти ExecutionState в Runtime Redis при редиспатче).
     * </pre>
     *
     * <code>string message_id = 7;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      messageId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Только для BACKGROUND_TASK_TYPE_STAGE_RETRY — `source_event_id` там не
     * подходит по смыслу (для остальных двух типов это event_id ЧУЖОГО
     * события-источника, здесь же нужен именно message_id самого Pipeline
     * Engine, чтобы найти ExecutionState в Runtime Redis при редиспатче).
     * </pre>
     *
     * <code>string message_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      messageId_ = getDefaultInstance().getMessageId();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Только для BACKGROUND_TASK_TYPE_STAGE_RETRY — `source_event_id` там не
     * подходит по смыслу (для остальных двух типов это event_id ЧУЖОГО
     * события-источника, здесь же нужен именно message_id самого Pipeline
     * Engine, чтобы найти ExecutionState в Runtime Redis при редиспатче).
     * </pre>
     *
     * <code>string message_id = 7;</code>
     * @param value The bytes for messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      messageId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:mpp.events.v1.SchedulerBackgroundTask)
  }

  // @@protoc_insertion_point(class_scope:mpp.events.v1.SchedulerBackgroundTask)
  private static final uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask();
  }

  public static uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SchedulerBackgroundTask>
      PARSER = new com.google.protobuf.AbstractParser<SchedulerBackgroundTask>() {
    @java.lang.Override
    public SchedulerBackgroundTask parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SchedulerBackgroundTask> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SchedulerBackgroundTask> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uz.mpp.platformcontracts.events.v1.SchedulerBackgroundTask getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

