// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/scheduler_events.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.events.v1;

@com.google.protobuf.Generated
public interface SchedulerCriticalCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.events.v1.SchedulerCriticalCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stage_execution_id = 1;</code>
   * @return The stageExecutionId.
   */
  java.lang.String getStageExecutionId();
  /**
   * <code>string stage_execution_id = 1;</code>
   * @return The bytes for stageExecutionId.
   */
  com.google.protobuf.ByteString
      getStageExecutionIdBytes();

  /**
   * <code>.mpp.common.v1.CriticalCommandType task_type = 2;</code>
   * @return The enum numeric value on the wire for taskType.
   */
  int getTaskTypeValue();
  /**
   * <code>.mpp.common.v1.CriticalCommandType task_type = 2;</code>
   * @return The taskType.
   */
  uz.mpp.platformcontracts.common.v1.CriticalCommandType getTaskType();

  /**
   * <code>string requested_by = 3;</code>
   * @return The requestedBy.
   */
  java.lang.String getRequestedBy();
  /**
   * <code>string requested_by = 3;</code>
   * @return The bytes for requestedBy.
   */
  com.google.protobuf.ByteString
      getRequestedByBytes();

  /**
   * <code>string reason = 4;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 4;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>.google.protobuf.Timestamp requested_at = 5;</code>
   * @return Whether the requestedAt field is set.
   */
  boolean hasRequestedAt();
  /**
   * <code>.google.protobuf.Timestamp requested_at = 5;</code>
   * @return The requestedAt.
   */
  com.google.protobuf.Timestamp getRequestedAt();
  /**
   * <code>.google.protobuf.Timestamp requested_at = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getRequestedAtOrBuilder();
}
