// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/enums.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

/**
 * <pre>
 * account_state Billing Redis (HLD §15.3).
 * </pre>
 *
 * Protobuf enum {@code mpp.common.v1.AccountState}
 */
@com.google.protobuf.Generated
public enum AccountState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ACCOUNT_STATE_UNSPECIFIED = 0;</code>
   */
  ACCOUNT_STATE_UNSPECIFIED(0),
  /**
   * <code>ACCOUNT_STATE_ACTIVE = 1;</code>
   */
  ACCOUNT_STATE_ACTIVE(1),
  /**
   * <code>ACCOUNT_STATE_FROZEN = 2;</code>
   */
  ACCOUNT_STATE_FROZEN(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "AccountState");
  }
  /**
   * <code>ACCOUNT_STATE_UNSPECIFIED = 0;</code>
   */
  public static final int ACCOUNT_STATE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>ACCOUNT_STATE_ACTIVE = 1;</code>
   */
  public static final int ACCOUNT_STATE_ACTIVE_VALUE = 1;
  /**
   * <code>ACCOUNT_STATE_FROZEN = 2;</code>
   */
  public static final int ACCOUNT_STATE_FROZEN_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AccountState valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AccountState forNumber(int value) {
    switch (value) {
      case 0: return ACCOUNT_STATE_UNSPECIFIED;
      case 1: return ACCOUNT_STATE_ACTIVE;
      case 2: return ACCOUNT_STATE_FROZEN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AccountState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AccountState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AccountState>() {
          public AccountState findValueByNumber(int number) {
            return AccountState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return uz.mpp.platformcontracts.common.v1.Enums.getDescriptor().getEnumType(8);
  }

  private static final AccountState[] VALUES = values();

  public static AccountState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AccountState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:mpp.common.v1.AccountState)
}

