// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/enums.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

/**
 * <pre>
 * Тип задачи Scheduler Background Lane (HLD §9.3, §14, §19).
 * </pre>
 *
 * Protobuf enum {@code mpp.common.v1.BackgroundTaskType}
 */
@com.google.protobuf.Generated
public enum BackgroundTaskType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>BACKGROUND_TASK_TYPE_UNSPECIFIED = 0;</code>
   */
  BACKGROUND_TASK_TYPE_UNSPECIFIED(0),
  /**
   * <code>BACKGROUND_TASK_TYPE_DLR_CORRELATION_RETRY = 1;</code>
   */
  BACKGROUND_TASK_TYPE_DLR_CORRELATION_RETRY(1),
  /**
   * <code>BACKGROUND_TASK_TYPE_NOTIFICATION_RETRY = 2;</code>
   */
  BACKGROUND_TASK_TYPE_NOTIFICATION_RETRY(2),
  /**
   * <pre>
   * Отложенный редиспатч DELIVERY-стадии после транзиентного отказа
   * (TPS_THROTTLED/PACER_QUEUE_FULL/PACER_QUEUE_TIMEOUT и т.п., см.
   * Pipeline Engine execution_state.rs Decision::RetryLater), пока TTL
   * сообщения не истёк — публикуется Pipeline Engine, потребляется им же
   * (через pipeline.retry.triggers) после отработки задержки Background Lane.
   * </pre>
   *
   * <code>BACKGROUND_TASK_TYPE_STAGE_RETRY = 3;</code>
   */
  BACKGROUND_TASK_TYPE_STAGE_RETRY(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "BackgroundTaskType");
  }
  /**
   * <code>BACKGROUND_TASK_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int BACKGROUND_TASK_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>BACKGROUND_TASK_TYPE_DLR_CORRELATION_RETRY = 1;</code>
   */
  public static final int BACKGROUND_TASK_TYPE_DLR_CORRELATION_RETRY_VALUE = 1;
  /**
   * <code>BACKGROUND_TASK_TYPE_NOTIFICATION_RETRY = 2;</code>
   */
  public static final int BACKGROUND_TASK_TYPE_NOTIFICATION_RETRY_VALUE = 2;
  /**
   * <pre>
   * Отложенный редиспатч DELIVERY-стадии после транзиентного отказа
   * (TPS_THROTTLED/PACER_QUEUE_FULL/PACER_QUEUE_TIMEOUT и т.п., см.
   * Pipeline Engine execution_state.rs Decision::RetryLater), пока TTL
   * сообщения не истёк — публикуется Pipeline Engine, потребляется им же
   * (через pipeline.retry.triggers) после отработки задержки Background Lane.
   * </pre>
   *
   * <code>BACKGROUND_TASK_TYPE_STAGE_RETRY = 3;</code>
   */
  public static final int BACKGROUND_TASK_TYPE_STAGE_RETRY_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static BackgroundTaskType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static BackgroundTaskType forNumber(int value) {
    switch (value) {
      case 0: return BACKGROUND_TASK_TYPE_UNSPECIFIED;
      case 1: return BACKGROUND_TASK_TYPE_DLR_CORRELATION_RETRY;
      case 2: return BACKGROUND_TASK_TYPE_NOTIFICATION_RETRY;
      case 3: return BACKGROUND_TASK_TYPE_STAGE_RETRY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<BackgroundTaskType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      BackgroundTaskType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<BackgroundTaskType>() {
          public BackgroundTaskType findValueByNumber(int number) {
            return BackgroundTaskType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return uz.mpp.platformcontracts.common.v1.Enums.getDescriptor().getEnumType(10);
  }

  private static final BackgroundTaskType[] VALUES = values();

  public static BackgroundTaskType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private BackgroundTaskType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:mpp.common.v1.BackgroundTaskType)
}

