// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/stage_contract.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

@com.google.protobuf.Generated
public interface BillingExtensionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.common.v1.BillingExtension)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resolved_operator_id = 1;</code>
   * @return The resolvedOperatorId.
   */
  java.lang.String getResolvedOperatorId();
  /**
   * <code>string resolved_operator_id = 1;</code>
   * @return The bytes for resolvedOperatorId.
   */
  com.google.protobuf.ByteString
      getResolvedOperatorIdBytes();

  /**
   * <pre>
   * Посчитано Pipeline Engine при кэшировании контекста — Billing не читает
   * msgctx за этим полем (service_internal_methods.md §0).
   * </pre>
   *
   * <code>int32 segment_count = 2;</code>
   * @return The segmentCount.
   */
  int getSegmentCount();

  /**
   * <pre>
   * Категория, присвоенная Policy — обычная (из шаблона), либо одно из
   * двух специальных значений: "UNTEMPLATED" (нет совпадения, но партнёр
   * разрешил продолжить) или "BLOCKED" (Policy отклонил — тариф на
   * отклонённое сообщение тоже ненулевой). Billing только считает цену
   * по category, не принимает решение о том, продолжать ли pipeline —
   * это решает граф Pipeline Engine (см. открытый вопрос ниже).
   * </pre>
   *
   * <code>string category = 3;</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <pre>
   * Категория, присвоенная Policy — обычная (из шаблона), либо одно из
   * двух специальных значений: "UNTEMPLATED" (нет совпадения, но партнёр
   * разрешил продолжить) или "BLOCKED" (Policy отклонил — тариф на
   * отклонённое сообщение тоже ненулевой). Billing только считает цену
   * по category, не принимает решение о том, продолжать ли pipeline —
   * это решает граф Pipeline Engine (см. открытый вопрос ниже).
   * </pre>
   *
   * <code>string category = 3;</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();
}
