// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/stage_contract.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

/**
 * Protobuf type {@code mpp.common.v1.BillingResult}
 */
@com.google.protobuf.Generated
public final class BillingResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:mpp.common.v1.BillingResult)
    BillingResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "BillingResult");
  }
  // Use BillingResult.newBuilder() to construct.
  private BillingResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BillingResult() {
    chargeId_ = "";
    category_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_BillingResult_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_BillingResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_BillingResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uz.mpp.platformcontracts.common.v1.BillingResult.class, uz.mpp.platformcontracts.common.v1.BillingResult.Builder.class);
  }

  private int bitField0_;
  public static final int CHARGE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object chargeId_ = "";
  /**
   * <pre>
   * charge_id = stage_execution_id (HLD §15.1/§15.4) — поле дублирует
   * stage_execution_id ради самодостаточности события для аудита.
   * </pre>
   *
   * <code>string charge_id = 1;</code>
   * @return The chargeId.
   */
  @java.lang.Override
  public java.lang.String getChargeId() {
    java.lang.Object ref = chargeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chargeId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * charge_id = stage_execution_id (HLD §15.1/§15.4) — поле дублирует
   * stage_execution_id ради самодостаточности события для аудита.
   * </pre>
   *
   * <code>string charge_id = 1;</code>
   * @return The bytes for chargeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChargeIdBytes() {
    java.lang.Object ref = chargeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chargeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORY_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object category_ = "";
  /**
   * <pre>
   * Эхо категории, с которой был вызван Billing — избавляет downstream
   * (Analytics Writer, ClickHouse-отчётность) от необходимости
   * сопоставлять с диспетчеризацией, чтобы узнать, что было оплачено.
   * </pre>
   *
   * <code>string category = 4;</code>
   * @return The category.
   */
  @java.lang.Override
  public java.lang.String getCategory() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      category_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Эхо категории, с которой был вызван Billing — избавляет downstream
   * (Analytics Writer, ClickHouse-отчётность) от необходимости
   * сопоставлять с диспетчеризацией, чтобы узнать, что было оплачено.
   * </pre>
   *
   * <code>string category = 4;</code>
   * @return The bytes for category.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCategoryBytes() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      category_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 2;
  private uz.mpp.platformcontracts.common.v1.Money amount_;
  /**
   * <code>.mpp.common.v1.Money amount = 2;</code>
   * @return Whether the amount field is set.
   */
  @java.lang.Override
  public boolean hasAmount() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.mpp.common.v1.Money amount = 2;</code>
   * @return The amount.
   */
  @java.lang.Override
  public uz.mpp.platformcontracts.common.v1.Money getAmount() {
    return amount_ == null ? uz.mpp.platformcontracts.common.v1.Money.getDefaultInstance() : amount_;
  }
  /**
   * <code>.mpp.common.v1.Money amount = 2;</code>
   */
  @java.lang.Override
  public uz.mpp.platformcontracts.common.v1.MoneyOrBuilder getAmountOrBuilder() {
    return amount_ == null ? uz.mpp.platformcontracts.common.v1.Money.getDefaultInstance() : amount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(chargeId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, chargeId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getAmount());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(category_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, category_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(chargeId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, chargeId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAmount());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(category_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, category_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uz.mpp.platformcontracts.common.v1.BillingResult)) {
      return super.equals(obj);
    }
    uz.mpp.platformcontracts.common.v1.BillingResult other = (uz.mpp.platformcontracts.common.v1.BillingResult) obj;

    if (!getChargeId()
        .equals(other.getChargeId())) return false;
    if (!getCategory()
        .equals(other.getCategory())) return false;
    if (hasAmount() != other.hasAmount()) return false;
    if (hasAmount()) {
      if (!getAmount()
          .equals(other.getAmount())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHARGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getChargeId().hashCode();
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + getCategory().hashCode();
    if (hasAmount()) {
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uz.mpp.platformcontracts.common.v1.BillingResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.common.v1.BillingResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.BillingResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.common.v1.BillingResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.BillingResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.common.v1.BillingResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.BillingResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.common.v1.BillingResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static uz.mpp.platformcontracts.common.v1.BillingResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static uz.mpp.platformcontracts.common.v1.BillingResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.BillingResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.common.v1.BillingResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uz.mpp.platformcontracts.common.v1.BillingResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mpp.common.v1.BillingResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mpp.common.v1.BillingResult)
      uz.mpp.platformcontracts.common.v1.BillingResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_BillingResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_BillingResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uz.mpp.platformcontracts.common.v1.BillingResult.class, uz.mpp.platformcontracts.common.v1.BillingResult.Builder.class);
    }

    // Construct using uz.mpp.platformcontracts.common.v1.BillingResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetAmountFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      chargeId_ = "";
      category_ = "";
      amount_ = null;
      if (amountBuilder_ != null) {
        amountBuilder_.dispose();
        amountBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_BillingResult_descriptor;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.BillingResult getDefaultInstanceForType() {
      return uz.mpp.platformcontracts.common.v1.BillingResult.getDefaultInstance();
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.BillingResult build() {
      uz.mpp.platformcontracts.common.v1.BillingResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.BillingResult buildPartial() {
      uz.mpp.platformcontracts.common.v1.BillingResult result = new uz.mpp.platformcontracts.common.v1.BillingResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(uz.mpp.platformcontracts.common.v1.BillingResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.chargeId_ = chargeId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.category_ = category_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.amount_ = amountBuilder_ == null
            ? amount_
            : amountBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uz.mpp.platformcontracts.common.v1.BillingResult) {
        return mergeFrom((uz.mpp.platformcontracts.common.v1.BillingResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uz.mpp.platformcontracts.common.v1.BillingResult other) {
      if (other == uz.mpp.platformcontracts.common.v1.BillingResult.getDefaultInstance()) return this;
      if (!other.getChargeId().isEmpty()) {
        chargeId_ = other.chargeId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getCategory().isEmpty()) {
        category_ = other.category_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasAmount()) {
        mergeAmount(other.getAmount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              chargeId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetAmountFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 18
            case 34: {
              category_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object chargeId_ = "";
    /**
     * <pre>
     * charge_id = stage_execution_id (HLD §15.1/§15.4) — поле дублирует
     * stage_execution_id ради самодостаточности события для аудита.
     * </pre>
     *
     * <code>string charge_id = 1;</code>
     * @return The chargeId.
     */
    public java.lang.String getChargeId() {
      java.lang.Object ref = chargeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chargeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * charge_id = stage_execution_id (HLD §15.1/§15.4) — поле дублирует
     * stage_execution_id ради самодостаточности события для аудита.
     * </pre>
     *
     * <code>string charge_id = 1;</code>
     * @return The bytes for chargeId.
     */
    public com.google.protobuf.ByteString
        getChargeIdBytes() {
      java.lang.Object ref = chargeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chargeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * charge_id = stage_execution_id (HLD §15.1/§15.4) — поле дублирует
     * stage_execution_id ради самодостаточности события для аудита.
     * </pre>
     *
     * <code>string charge_id = 1;</code>
     * @param value The chargeId to set.
     * @return This builder for chaining.
     */
    public Builder setChargeId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      chargeId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * charge_id = stage_execution_id (HLD §15.1/§15.4) — поле дублирует
     * stage_execution_id ради самодостаточности события для аудита.
     * </pre>
     *
     * <code>string charge_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearChargeId() {
      chargeId_ = getDefaultInstance().getChargeId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * charge_id = stage_execution_id (HLD §15.1/§15.4) — поле дублирует
     * stage_execution_id ради самодостаточности события для аудита.
     * </pre>
     *
     * <code>string charge_id = 1;</code>
     * @param value The bytes for chargeId to set.
     * @return This builder for chaining.
     */
    public Builder setChargeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      chargeId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object category_ = "";
    /**
     * <pre>
     * Эхо категории, с которой был вызван Billing — избавляет downstream
     * (Analytics Writer, ClickHouse-отчётность) от необходимости
     * сопоставлять с диспетчеризацией, чтобы узнать, что было оплачено.
     * </pre>
     *
     * <code>string category = 4;</code>
     * @return The category.
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Эхо категории, с которой был вызван Billing — избавляет downstream
     * (Analytics Writer, ClickHouse-отчётность) от необходимости
     * сопоставлять с диспетчеризацией, чтобы узнать, что было оплачено.
     * </pre>
     *
     * <code>string category = 4;</code>
     * @return The bytes for category.
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Эхо категории, с которой был вызван Billing — избавляет downstream
     * (Analytics Writer, ClickHouse-отчётность) от необходимости
     * сопоставлять с диспетчеризацией, чтобы узнать, что было оплачено.
     * </pre>
     *
     * <code>string category = 4;</code>
     * @param value The category to set.
     * @return This builder for chaining.
     */
    public Builder setCategory(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      category_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Эхо категории, с которой был вызван Billing — избавляет downstream
     * (Analytics Writer, ClickHouse-отчётность) от необходимости
     * сопоставлять с диспетчеризацией, чтобы узнать, что было оплачено.
     * </pre>
     *
     * <code>string category = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategory() {
      category_ = getDefaultInstance().getCategory();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Эхо категории, с которой был вызван Billing — избавляет downstream
     * (Analytics Writer, ClickHouse-отчётность) от необходимости
     * сопоставлять с диспетчеризацией, чтобы узнать, что было оплачено.
     * </pre>
     *
     * <code>string category = 4;</code>
     * @param value The bytes for category to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      category_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private uz.mpp.platformcontracts.common.v1.Money amount_;
    private com.google.protobuf.SingleFieldBuilder<
        uz.mpp.platformcontracts.common.v1.Money, uz.mpp.platformcontracts.common.v1.Money.Builder, uz.mpp.platformcontracts.common.v1.MoneyOrBuilder> amountBuilder_;
    /**
     * <code>.mpp.common.v1.Money amount = 2;</code>
     * @return Whether the amount field is set.
     */
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.mpp.common.v1.Money amount = 2;</code>
     * @return The amount.
     */
    public uz.mpp.platformcontracts.common.v1.Money getAmount() {
      if (amountBuilder_ == null) {
        return amount_ == null ? uz.mpp.platformcontracts.common.v1.Money.getDefaultInstance() : amount_;
      } else {
        return amountBuilder_.getMessage();
      }
    }
    /**
     * <code>.mpp.common.v1.Money amount = 2;</code>
     */
    public Builder setAmount(uz.mpp.platformcontracts.common.v1.Money value) {
      if (amountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        amount_ = value;
      } else {
        amountBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.mpp.common.v1.Money amount = 2;</code>
     */
    public Builder setAmount(
        uz.mpp.platformcontracts.common.v1.Money.Builder builderForValue) {
      if (amountBuilder_ == null) {
        amount_ = builderForValue.build();
      } else {
        amountBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.mpp.common.v1.Money amount = 2;</code>
     */
    public Builder mergeAmount(uz.mpp.platformcontracts.common.v1.Money value) {
      if (amountBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          amount_ != null &&
          amount_ != uz.mpp.platformcontracts.common.v1.Money.getDefaultInstance()) {
          getAmountBuilder().mergeFrom(value);
        } else {
          amount_ = value;
        }
      } else {
        amountBuilder_.mergeFrom(value);
      }
      if (amount_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.mpp.common.v1.Money amount = 2;</code>
     */
    public Builder clearAmount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      amount_ = null;
      if (amountBuilder_ != null) {
        amountBuilder_.dispose();
        amountBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mpp.common.v1.Money amount = 2;</code>
     */
    public uz.mpp.platformcontracts.common.v1.Money.Builder getAmountBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetAmountFieldBuilder().getBuilder();
    }
    /**
     * <code>.mpp.common.v1.Money amount = 2;</code>
     */
    public uz.mpp.platformcontracts.common.v1.MoneyOrBuilder getAmountOrBuilder() {
      if (amountBuilder_ != null) {
        return amountBuilder_.getMessageOrBuilder();
      } else {
        return amount_ == null ?
            uz.mpp.platformcontracts.common.v1.Money.getDefaultInstance() : amount_;
      }
    }
    /**
     * <code>.mpp.common.v1.Money amount = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        uz.mpp.platformcontracts.common.v1.Money, uz.mpp.platformcontracts.common.v1.Money.Builder, uz.mpp.platformcontracts.common.v1.MoneyOrBuilder> 
        internalGetAmountFieldBuilder() {
      if (amountBuilder_ == null) {
        amountBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            uz.mpp.platformcontracts.common.v1.Money, uz.mpp.platformcontracts.common.v1.Money.Builder, uz.mpp.platformcontracts.common.v1.MoneyOrBuilder>(
                getAmount(),
                getParentForChildren(),
                isClean());
        amount_ = null;
      }
      return amountBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:mpp.common.v1.BillingResult)
  }

  // @@protoc_insertion_point(class_scope:mpp.common.v1.BillingResult)
  private static final uz.mpp.platformcontracts.common.v1.BillingResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uz.mpp.platformcontracts.common.v1.BillingResult();
  }

  public static uz.mpp.platformcontracts.common.v1.BillingResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BillingResult>
      PARSER = new com.google.protobuf.AbstractParser<BillingResult>() {
    @java.lang.Override
    public BillingResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BillingResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BillingResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uz.mpp.platformcontracts.common.v1.BillingResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

