// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/enums.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

/**
 * <pre>
 * entity_type конфигурационных сущностей в config.changes (HLD §16,
 * data_infrastructure_spec.md §1.1, §1.9a-c).
 * </pre>
 *
 * Protobuf enum {@code mpp.common.v1.ConfigEntityType}
 */
@com.google.protobuf.Generated
public enum ConfigEntityType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CONFIG_ENTITY_TYPE_UNSPECIFIED = 0;</code>
   */
  CONFIG_ENTITY_TYPE_UNSPECIFIED(0),
  /**
   * <code>CONFIG_ENTITY_TYPE_PIPELINE = 1;</code>
   */
  CONFIG_ENTITY_TYPE_PIPELINE(1),
  /**
   * <code>CONFIG_ENTITY_TYPE_POLICY_RULESET = 2;</code>
   */
  CONFIG_ENTITY_TYPE_POLICY_RULESET(2),
  /**
   * <code>CONFIG_ENTITY_TYPE_POLICY_TEMPLATE = 3;</code>
   */
  CONFIG_ENTITY_TYPE_POLICY_TEMPLATE(3),
  /**
   * <code>CONFIG_ENTITY_TYPE_BILLING_TARIFF = 4;</code>
   */
  CONFIG_ENTITY_TYPE_BILLING_TARIFF(4),
  /**
   * <code>CONFIG_ENTITY_TYPE_ROUTING_TABLE = 5;</code>
   */
  CONFIG_ENTITY_TYPE_ROUTING_TABLE(5),
  /**
   * <code>CONFIG_ENTITY_TYPE_NUMBER_RANGE = 6;</code>
   */
  CONFIG_ENTITY_TYPE_NUMBER_RANGE(6),
  /**
   * <code>CONFIG_ENTITY_TYPE_PARTNER = 7;</code>
   */
  CONFIG_ENTITY_TYPE_PARTNER(7),
  /**
   * <code>CONFIG_ENTITY_TYPE_OPERATOR = 8;</code>
   */
  CONFIG_ENTITY_TYPE_OPERATOR(8),
  /**
   * <code>CONFIG_ENTITY_TYPE_SUBSCRIBER_CONSENT = 9;</code>
   */
  CONFIG_ENTITY_TYPE_SUBSCRIBER_CONSENT(9),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ConfigEntityType");
  }
  /**
   * <code>CONFIG_ENTITY_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int CONFIG_ENTITY_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>CONFIG_ENTITY_TYPE_PIPELINE = 1;</code>
   */
  public static final int CONFIG_ENTITY_TYPE_PIPELINE_VALUE = 1;
  /**
   * <code>CONFIG_ENTITY_TYPE_POLICY_RULESET = 2;</code>
   */
  public static final int CONFIG_ENTITY_TYPE_POLICY_RULESET_VALUE = 2;
  /**
   * <code>CONFIG_ENTITY_TYPE_POLICY_TEMPLATE = 3;</code>
   */
  public static final int CONFIG_ENTITY_TYPE_POLICY_TEMPLATE_VALUE = 3;
  /**
   * <code>CONFIG_ENTITY_TYPE_BILLING_TARIFF = 4;</code>
   */
  public static final int CONFIG_ENTITY_TYPE_BILLING_TARIFF_VALUE = 4;
  /**
   * <code>CONFIG_ENTITY_TYPE_ROUTING_TABLE = 5;</code>
   */
  public static final int CONFIG_ENTITY_TYPE_ROUTING_TABLE_VALUE = 5;
  /**
   * <code>CONFIG_ENTITY_TYPE_NUMBER_RANGE = 6;</code>
   */
  public static final int CONFIG_ENTITY_TYPE_NUMBER_RANGE_VALUE = 6;
  /**
   * <code>CONFIG_ENTITY_TYPE_PARTNER = 7;</code>
   */
  public static final int CONFIG_ENTITY_TYPE_PARTNER_VALUE = 7;
  /**
   * <code>CONFIG_ENTITY_TYPE_OPERATOR = 8;</code>
   */
  public static final int CONFIG_ENTITY_TYPE_OPERATOR_VALUE = 8;
  /**
   * <code>CONFIG_ENTITY_TYPE_SUBSCRIBER_CONSENT = 9;</code>
   */
  public static final int CONFIG_ENTITY_TYPE_SUBSCRIBER_CONSENT_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ConfigEntityType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ConfigEntityType forNumber(int value) {
    switch (value) {
      case 0: return CONFIG_ENTITY_TYPE_UNSPECIFIED;
      case 1: return CONFIG_ENTITY_TYPE_PIPELINE;
      case 2: return CONFIG_ENTITY_TYPE_POLICY_RULESET;
      case 3: return CONFIG_ENTITY_TYPE_POLICY_TEMPLATE;
      case 4: return CONFIG_ENTITY_TYPE_BILLING_TARIFF;
      case 5: return CONFIG_ENTITY_TYPE_ROUTING_TABLE;
      case 6: return CONFIG_ENTITY_TYPE_NUMBER_RANGE;
      case 7: return CONFIG_ENTITY_TYPE_PARTNER;
      case 8: return CONFIG_ENTITY_TYPE_OPERATOR;
      case 9: return CONFIG_ENTITY_TYPE_SUBSCRIBER_CONSENT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ConfigEntityType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ConfigEntityType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ConfigEntityType>() {
          public ConfigEntityType findValueByNumber(int number) {
            return ConfigEntityType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return uz.mpp.platformcontracts.common.v1.Enums.getDescriptor().getEnumType(13);
  }

  private static final ConfigEntityType[] VALUES = values();

  public static ConfigEntityType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ConfigEntityType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:mpp.common.v1.ConfigEntityType)
}

