// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/enums.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

/**
 * <pre>
 * Тип ручной команды Scheduler Critical Sweep (HLD §9.1).
 * </pre>
 *
 * Protobuf enum {@code mpp.common.v1.CriticalCommandType}
 */
@com.google.protobuf.Generated
public enum CriticalCommandType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CRITICAL_COMMAND_TYPE_UNSPECIFIED = 0;</code>
   */
  CRITICAL_COMMAND_TYPE_UNSPECIFIED(0),
  /**
   * <code>CRITICAL_COMMAND_TYPE_FORCE_TIMEOUT = 1;</code>
   */
  CRITICAL_COMMAND_TYPE_FORCE_TIMEOUT(1),
  /**
   * <code>CRITICAL_COMMAND_TYPE_FORCE_RETRY = 2;</code>
   */
  CRITICAL_COMMAND_TYPE_FORCE_RETRY(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "CriticalCommandType");
  }
  /**
   * <code>CRITICAL_COMMAND_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int CRITICAL_COMMAND_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>CRITICAL_COMMAND_TYPE_FORCE_TIMEOUT = 1;</code>
   */
  public static final int CRITICAL_COMMAND_TYPE_FORCE_TIMEOUT_VALUE = 1;
  /**
   * <code>CRITICAL_COMMAND_TYPE_FORCE_RETRY = 2;</code>
   */
  public static final int CRITICAL_COMMAND_TYPE_FORCE_RETRY_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CriticalCommandType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CriticalCommandType forNumber(int value) {
    switch (value) {
      case 0: return CRITICAL_COMMAND_TYPE_UNSPECIFIED;
      case 1: return CRITICAL_COMMAND_TYPE_FORCE_TIMEOUT;
      case 2: return CRITICAL_COMMAND_TYPE_FORCE_RETRY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CriticalCommandType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CriticalCommandType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CriticalCommandType>() {
          public CriticalCommandType findValueByNumber(int number) {
            return CriticalCommandType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return uz.mpp.platformcontracts.common.v1.Enums.getDescriptor().getEnumType(11);
  }

  private static final CriticalCommandType[] VALUES = values();

  public static CriticalCommandType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CriticalCommandType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:mpp.common.v1.CriticalCommandType)
}

