// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/stage_contract.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

@com.google.protobuf.Generated
public interface DeliveryResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.common.v1.DeliveryResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string queue_msg_id = 1;</code>
   * @return The queueMsgId.
   */
  java.lang.String getQueueMsgId();
  /**
   * <code>string queue_msg_id = 1;</code>
   * @return The bytes for queueMsgId.
   */
  com.google.protobuf.ByteString
      getQueueMsgIdBytes();
}
