// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/stage_contract.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

/**
 * Protobuf type {@code mpp.common.v1.DeliveryReconciliationExtension}
 */
@com.google.protobuf.Generated
public final class DeliveryReconciliationExtension extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:mpp.common.v1.DeliveryReconciliationExtension)
    DeliveryReconciliationExtensionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "DeliveryReconciliationExtension");
  }
  // Use DeliveryReconciliationExtension.newBuilder() to construct.
  private DeliveryReconciliationExtension(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DeliveryReconciliationExtension() {
    triggeringOutcome_ = 0;
    queueMsgId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_DeliveryReconciliationExtension_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_DeliveryReconciliationExtension_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_DeliveryReconciliationExtension_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension.class, uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension.Builder.class);
  }

  public static final int TRIGGERING_OUTCOME_FIELD_NUMBER = 1;
  private int triggeringOutcome_ = 0;
  /**
   * <pre>
   * Почему сообщение попало в reconciliation — сегодня всегда
   * SUBMISSION_OUTCOME_UNKNOWN, поле оставлено расширяемым.
   * </pre>
   *
   * <code>.mpp.common.v1.Outcome triggering_outcome = 1;</code>
   * @return The enum numeric value on the wire for triggeringOutcome.
   */
  @java.lang.Override public int getTriggeringOutcomeValue() {
    return triggeringOutcome_;
  }
  /**
   * <pre>
   * Почему сообщение попало в reconciliation — сегодня всегда
   * SUBMISSION_OUTCOME_UNKNOWN, поле оставлено расширяемым.
   * </pre>
   *
   * <code>.mpp.common.v1.Outcome triggering_outcome = 1;</code>
   * @return The triggeringOutcome.
   */
  @java.lang.Override public uz.mpp.platformcontracts.common.v1.Outcome getTriggeringOutcome() {
    uz.mpp.platformcontracts.common.v1.Outcome result = uz.mpp.platformcontracts.common.v1.Outcome.forNumber(triggeringOutcome_);
    return result == null ? uz.mpp.platformcontracts.common.v1.Outcome.UNRECOGNIZED : result;
  }

  public static final int QUEUE_MSG_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object queueMsgId_ = "";
  /**
   * <code>string queue_msg_id = 2;</code>
   * @return The queueMsgId.
   */
  @java.lang.Override
  public java.lang.String getQueueMsgId() {
    java.lang.Object ref = queueMsgId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      queueMsgId_ = s;
      return s;
    }
  }
  /**
   * <code>string queue_msg_id = 2;</code>
   * @return The bytes for queueMsgId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQueueMsgIdBytes() {
    java.lang.Object ref = queueMsgId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      queueMsgId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (triggeringOutcome_ != uz.mpp.platformcontracts.common.v1.Outcome.OUTCOME_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, triggeringOutcome_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(queueMsgId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, queueMsgId_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (triggeringOutcome_ != uz.mpp.platformcontracts.common.v1.Outcome.OUTCOME_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, triggeringOutcome_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(queueMsgId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, queueMsgId_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension)) {
      return super.equals(obj);
    }
    uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension other = (uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension) obj;

    if (triggeringOutcome_ != other.triggeringOutcome_) return false;
    if (!getQueueMsgId()
        .equals(other.getQueueMsgId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRIGGERING_OUTCOME_FIELD_NUMBER;
    hash = (53 * hash) + triggeringOutcome_;
    hash = (37 * hash) + QUEUE_MSG_ID_FIELD_NUMBER;
    hash = (53 * hash) + getQueueMsgId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mpp.common.v1.DeliveryReconciliationExtension}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mpp.common.v1.DeliveryReconciliationExtension)
      uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtensionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_DeliveryReconciliationExtension_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_DeliveryReconciliationExtension_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension.class, uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension.Builder.class);
    }

    // Construct using uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      triggeringOutcome_ = 0;
      queueMsgId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_DeliveryReconciliationExtension_descriptor;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension getDefaultInstanceForType() {
      return uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension.getDefaultInstance();
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension build() {
      uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension buildPartial() {
      uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension result = new uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.triggeringOutcome_ = triggeringOutcome_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.queueMsgId_ = queueMsgId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension) {
        return mergeFrom((uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension other) {
      if (other == uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension.getDefaultInstance()) return this;
      if (other.triggeringOutcome_ != 0) {
        setTriggeringOutcomeValue(other.getTriggeringOutcomeValue());
      }
      if (!other.getQueueMsgId().isEmpty()) {
        queueMsgId_ = other.queueMsgId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              triggeringOutcome_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              queueMsgId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int triggeringOutcome_ = 0;
    /**
     * <pre>
     * Почему сообщение попало в reconciliation — сегодня всегда
     * SUBMISSION_OUTCOME_UNKNOWN, поле оставлено расширяемым.
     * </pre>
     *
     * <code>.mpp.common.v1.Outcome triggering_outcome = 1;</code>
     * @return The enum numeric value on the wire for triggeringOutcome.
     */
    @java.lang.Override public int getTriggeringOutcomeValue() {
      return triggeringOutcome_;
    }
    /**
     * <pre>
     * Почему сообщение попало в reconciliation — сегодня всегда
     * SUBMISSION_OUTCOME_UNKNOWN, поле оставлено расширяемым.
     * </pre>
     *
     * <code>.mpp.common.v1.Outcome triggering_outcome = 1;</code>
     * @param value The enum numeric value on the wire for triggeringOutcome to set.
     * @return This builder for chaining.
     */
    public Builder setTriggeringOutcomeValue(int value) {
      triggeringOutcome_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Почему сообщение попало в reconciliation — сегодня всегда
     * SUBMISSION_OUTCOME_UNKNOWN, поле оставлено расширяемым.
     * </pre>
     *
     * <code>.mpp.common.v1.Outcome triggering_outcome = 1;</code>
     * @return The triggeringOutcome.
     */
    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.Outcome getTriggeringOutcome() {
      uz.mpp.platformcontracts.common.v1.Outcome result = uz.mpp.platformcontracts.common.v1.Outcome.forNumber(triggeringOutcome_);
      return result == null ? uz.mpp.platformcontracts.common.v1.Outcome.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Почему сообщение попало в reconciliation — сегодня всегда
     * SUBMISSION_OUTCOME_UNKNOWN, поле оставлено расширяемым.
     * </pre>
     *
     * <code>.mpp.common.v1.Outcome triggering_outcome = 1;</code>
     * @param value The triggeringOutcome to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setTriggeringOutcome(uz.mpp.platformcontracts.common.v1.Outcome value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      triggeringOutcome_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Почему сообщение попало в reconciliation — сегодня всегда
     * SUBMISSION_OUTCOME_UNKNOWN, поле оставлено расширяемым.
     * </pre>
     *
     * <code>.mpp.common.v1.Outcome triggering_outcome = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTriggeringOutcome() {
      bitField0_ = (bitField0_ & ~0x00000001);
      triggeringOutcome_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object queueMsgId_ = "";
    /**
     * <code>string queue_msg_id = 2;</code>
     * @return The queueMsgId.
     */
    public java.lang.String getQueueMsgId() {
      java.lang.Object ref = queueMsgId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        queueMsgId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string queue_msg_id = 2;</code>
     * @return The bytes for queueMsgId.
     */
    public com.google.protobuf.ByteString
        getQueueMsgIdBytes() {
      java.lang.Object ref = queueMsgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        queueMsgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string queue_msg_id = 2;</code>
     * @param value The queueMsgId to set.
     * @return This builder for chaining.
     */
    public Builder setQueueMsgId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      queueMsgId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string queue_msg_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearQueueMsgId() {
      queueMsgId_ = getDefaultInstance().getQueueMsgId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string queue_msg_id = 2;</code>
     * @param value The bytes for queueMsgId to set.
     * @return This builder for chaining.
     */
    public Builder setQueueMsgIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      queueMsgId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:mpp.common.v1.DeliveryReconciliationExtension)
  }

  // @@protoc_insertion_point(class_scope:mpp.common.v1.DeliveryReconciliationExtension)
  private static final uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension();
  }

  public static uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeliveryReconciliationExtension>
      PARSER = new com.google.protobuf.AbstractParser<DeliveryReconciliationExtension>() {
    @java.lang.Override
    public DeliveryReconciliationExtension parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DeliveryReconciliationExtension> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeliveryReconciliationExtension> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

