// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/enums.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

/**
 * <pre>
 * Основные исходы выполнения стадии (HLD §6).
 * </pre>
 *
 * Protobuf enum {@code mpp.common.v1.Outcome}
 */
@com.google.protobuf.Generated
public enum Outcome
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>OUTCOME_UNSPECIFIED = 0;</code>
   */
  OUTCOME_UNSPECIFIED(0),
  /**
   * <code>OUTCOME_SUCCEEDED = 1;</code>
   */
  OUTCOME_SUCCEEDED(1),
  /**
   * <code>OUTCOME_REJECTED = 2;</code>
   */
  OUTCOME_REJECTED(2),
  /**
   * <code>OUTCOME_FAILED = 3;</code>
   */
  OUTCOME_FAILED(3),
  /**
   * <code>OUTCOME_TIMED_OUT = 4;</code>
   */
  OUTCOME_TIMED_OUT(4),
  /**
   * <code>OUTCOME_RETRY_EXHAUSTED = 5;</code>
   */
  OUTCOME_RETRY_EXHAUSTED(5),
  /**
   * <code>OUTCOME_SUBMISSION_OUTCOME_UNKNOWN = 6;</code>
   */
  OUTCOME_SUBMISSION_OUTCOME_UNKNOWN(6),
  /**
   * <code>OUTCOME_DELIVERY_UNRESOLVED = 7;</code>
   */
  OUTCOME_DELIVERY_UNRESOLVED(7),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Outcome");
  }
  /**
   * <code>OUTCOME_UNSPECIFIED = 0;</code>
   */
  public static final int OUTCOME_UNSPECIFIED_VALUE = 0;
  /**
   * <code>OUTCOME_SUCCEEDED = 1;</code>
   */
  public static final int OUTCOME_SUCCEEDED_VALUE = 1;
  /**
   * <code>OUTCOME_REJECTED = 2;</code>
   */
  public static final int OUTCOME_REJECTED_VALUE = 2;
  /**
   * <code>OUTCOME_FAILED = 3;</code>
   */
  public static final int OUTCOME_FAILED_VALUE = 3;
  /**
   * <code>OUTCOME_TIMED_OUT = 4;</code>
   */
  public static final int OUTCOME_TIMED_OUT_VALUE = 4;
  /**
   * <code>OUTCOME_RETRY_EXHAUSTED = 5;</code>
   */
  public static final int OUTCOME_RETRY_EXHAUSTED_VALUE = 5;
  /**
   * <code>OUTCOME_SUBMISSION_OUTCOME_UNKNOWN = 6;</code>
   */
  public static final int OUTCOME_SUBMISSION_OUTCOME_UNKNOWN_VALUE = 6;
  /**
   * <code>OUTCOME_DELIVERY_UNRESOLVED = 7;</code>
   */
  public static final int OUTCOME_DELIVERY_UNRESOLVED_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Outcome valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Outcome forNumber(int value) {
    switch (value) {
      case 0: return OUTCOME_UNSPECIFIED;
      case 1: return OUTCOME_SUCCEEDED;
      case 2: return OUTCOME_REJECTED;
      case 3: return OUTCOME_FAILED;
      case 4: return OUTCOME_TIMED_OUT;
      case 5: return OUTCOME_RETRY_EXHAUSTED;
      case 6: return OUTCOME_SUBMISSION_OUTCOME_UNKNOWN;
      case 7: return OUTCOME_DELIVERY_UNRESOLVED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Outcome>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Outcome> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Outcome>() {
          public Outcome findValueByNumber(int number) {
            return Outcome.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return uz.mpp.platformcontracts.common.v1.Enums.getDescriptor().getEnumType(3);
  }

  private static final Outcome[] VALUES = values();

  public static Outcome valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Outcome(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:mpp.common.v1.Outcome)
}

