// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/stage_contract.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

/**
 * Protobuf type {@code mpp.common.v1.PolicyResult}
 */
@com.google.protobuf.Generated
public final class PolicyResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:mpp.common.v1.PolicyResult)
    PolicyResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "PolicyResult");
  }
  // Use PolicyResult.newBuilder() to construct.
  private PolicyResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PolicyResult() {
    category_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_PolicyResult_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_PolicyResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_PolicyResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uz.mpp.platformcontracts.common.v1.PolicyResult.class, uz.mpp.platformcontracts.common.v1.PolicyResult.Builder.class);
  }

  public static final int CATEGORY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object category_ = "";
  /**
   * <pre>
   * Присвоенная категория. Всегда заполнена, включая случай REJECTED:
   * "UNTEMPLATED" — нет совпадения с шаблоном, но партнёр разрешил
   * продолжить; "BLOCKED" — Policy отклонил сообщение (любая из 8 проверок,
   * HLD §5.3/§15 — единая категория и тариф независимо от конкретной
   * причины отклонения). Billing всегда получает непустую category.
   * </pre>
   *
   * <code>string category = 1;</code>
   * @return The category.
   */
  @java.lang.Override
  public java.lang.String getCategory() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      category_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Присвоенная категория. Всегда заполнена, включая случай REJECTED:
   * "UNTEMPLATED" — нет совпадения с шаблоном, но партнёр разрешил
   * продолжить; "BLOCKED" — Policy отклонил сообщение (любая из 8 проверок,
   * HLD §5.3/§15 — единая категория и тариф независимо от конкретной
   * причины отклонения). Billing всегда получает непустую category.
   * </pre>
   *
   * <code>string category = 1;</code>
   * @return The bytes for category.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCategoryBytes() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      category_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(category_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, category_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(category_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, category_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uz.mpp.platformcontracts.common.v1.PolicyResult)) {
      return super.equals(obj);
    }
    uz.mpp.platformcontracts.common.v1.PolicyResult other = (uz.mpp.platformcontracts.common.v1.PolicyResult) obj;

    if (!getCategory()
        .equals(other.getCategory())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + getCategory().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uz.mpp.platformcontracts.common.v1.PolicyResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.common.v1.PolicyResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.PolicyResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.common.v1.PolicyResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.PolicyResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.common.v1.PolicyResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.PolicyResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.common.v1.PolicyResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static uz.mpp.platformcontracts.common.v1.PolicyResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static uz.mpp.platformcontracts.common.v1.PolicyResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.PolicyResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.common.v1.PolicyResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uz.mpp.platformcontracts.common.v1.PolicyResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mpp.common.v1.PolicyResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mpp.common.v1.PolicyResult)
      uz.mpp.platformcontracts.common.v1.PolicyResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_PolicyResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_PolicyResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uz.mpp.platformcontracts.common.v1.PolicyResult.class, uz.mpp.platformcontracts.common.v1.PolicyResult.Builder.class);
    }

    // Construct using uz.mpp.platformcontracts.common.v1.PolicyResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      category_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_PolicyResult_descriptor;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.PolicyResult getDefaultInstanceForType() {
      return uz.mpp.platformcontracts.common.v1.PolicyResult.getDefaultInstance();
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.PolicyResult build() {
      uz.mpp.platformcontracts.common.v1.PolicyResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.PolicyResult buildPartial() {
      uz.mpp.platformcontracts.common.v1.PolicyResult result = new uz.mpp.platformcontracts.common.v1.PolicyResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(uz.mpp.platformcontracts.common.v1.PolicyResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.category_ = category_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uz.mpp.platformcontracts.common.v1.PolicyResult) {
        return mergeFrom((uz.mpp.platformcontracts.common.v1.PolicyResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uz.mpp.platformcontracts.common.v1.PolicyResult other) {
      if (other == uz.mpp.platformcontracts.common.v1.PolicyResult.getDefaultInstance()) return this;
      if (!other.getCategory().isEmpty()) {
        category_ = other.category_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              category_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object category_ = "";
    /**
     * <pre>
     * Присвоенная категория. Всегда заполнена, включая случай REJECTED:
     * "UNTEMPLATED" — нет совпадения с шаблоном, но партнёр разрешил
     * продолжить; "BLOCKED" — Policy отклонил сообщение (любая из 8 проверок,
     * HLD §5.3/§15 — единая категория и тариф независимо от конкретной
     * причины отклонения). Billing всегда получает непустую category.
     * </pre>
     *
     * <code>string category = 1;</code>
     * @return The category.
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Присвоенная категория. Всегда заполнена, включая случай REJECTED:
     * "UNTEMPLATED" — нет совпадения с шаблоном, но партнёр разрешил
     * продолжить; "BLOCKED" — Policy отклонил сообщение (любая из 8 проверок,
     * HLD §5.3/§15 — единая категория и тариф независимо от конкретной
     * причины отклонения). Billing всегда получает непустую category.
     * </pre>
     *
     * <code>string category = 1;</code>
     * @return The bytes for category.
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Присвоенная категория. Всегда заполнена, включая случай REJECTED:
     * "UNTEMPLATED" — нет совпадения с шаблоном, но партнёр разрешил
     * продолжить; "BLOCKED" — Policy отклонил сообщение (любая из 8 проверок,
     * HLD §5.3/§15 — единая категория и тариф независимо от конкретной
     * причины отклонения). Billing всегда получает непустую category.
     * </pre>
     *
     * <code>string category = 1;</code>
     * @param value The category to set.
     * @return This builder for chaining.
     */
    public Builder setCategory(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      category_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Присвоенная категория. Всегда заполнена, включая случай REJECTED:
     * "UNTEMPLATED" — нет совпадения с шаблоном, но партнёр разрешил
     * продолжить; "BLOCKED" — Policy отклонил сообщение (любая из 8 проверок,
     * HLD §5.3/§15 — единая категория и тариф независимо от конкретной
     * причины отклонения). Billing всегда получает непустую category.
     * </pre>
     *
     * <code>string category = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategory() {
      category_ = getDefaultInstance().getCategory();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Присвоенная категория. Всегда заполнена, включая случай REJECTED:
     * "UNTEMPLATED" — нет совпадения с шаблоном, но партнёр разрешил
     * продолжить; "BLOCKED" — Policy отклонил сообщение (любая из 8 проверок,
     * HLD §5.3/§15 — единая категория и тариф независимо от конкретной
     * причины отклонения). Billing всегда получает непустую category.
     * </pre>
     *
     * <code>string category = 1;</code>
     * @param value The bytes for category to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      category_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:mpp.common.v1.PolicyResult)
  }

  // @@protoc_insertion_point(class_scope:mpp.common.v1.PolicyResult)
  private static final uz.mpp.platformcontracts.common.v1.PolicyResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uz.mpp.platformcontracts.common.v1.PolicyResult();
  }

  public static uz.mpp.platformcontracts.common.v1.PolicyResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PolicyResult>
      PARSER = new com.google.protobuf.AbstractParser<PolicyResult>() {
    @java.lang.Override
    public PolicyResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PolicyResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PolicyResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uz.mpp.platformcontracts.common.v1.PolicyResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

