// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/stage_contract.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

@com.google.protobuf.Generated
public interface RoutingResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.common.v1.RoutingResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string route_id = 1;</code>
   * @return The routeId.
   */
  java.lang.String getRouteId();
  /**
   * <code>string route_id = 1;</code>
   * @return The bytes for routeId.
   */
  com.google.protobuf.ByteString
      getRouteIdBytes();

  /**
   * <code>.mpp.common.v1.Protocol protocol = 2;</code>
   * @return The enum numeric value on the wire for protocol.
   */
  int getProtocolValue();
  /**
   * <code>.mpp.common.v1.Protocol protocol = 2;</code>
   * @return The protocol.
   */
  uz.mpp.platformcontracts.common.v1.Protocol getProtocol();

  /**
   * <code>string route_version = 3;</code>
   * @return The routeVersion.
   */
  java.lang.String getRouteVersion();
  /**
   * <code>string route_version = 3;</code>
   * @return The bytes for routeVersion.
   */
  com.google.protobuf.ByteString
      getRouteVersionBytes();
}
