// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/stage_contract.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

@com.google.protobuf.Generated
public final class StageContract extends com.google.protobuf.GeneratedFile {
  private StageContract() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "StageContract");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_StageExecuteCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_StageExecuteCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_StageExecuteCommand_ConfigVersionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_StageExecuteCommand_ConfigVersionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_DestinationResolutionExtension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_DestinationResolutionExtension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_PolicyExtension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_PolicyExtension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_BillingExtension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_BillingExtension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_RoutingExtension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_RoutingExtension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_DeliveryExtension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_DeliveryExtension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_DeliveryReconciliationExtension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_DeliveryReconciliationExtension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_StageCompletedEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_StageCompletedEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_DestinationResolutionResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_DestinationResolutionResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_PolicyResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_PolicyResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_BillingResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_BillingResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_RoutingResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_RoutingResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_DeliveryResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_DeliveryResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_DeliveryReconciliationResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_DeliveryReconciliationResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033common/stage_contract.proto\022\rmpp.commo" +
      "n.v1\032\037google/protobuf/timestamp.proto\032\022c" +
      "ommon/enums.proto\032\022common/types.proto\"\267\007" +
      "\n\023StageExecuteCommand\022\020\n\010event_id\030\001 \001(\t\022" +
      "\022\n\nmessage_id\030\002 \001(\t\022\'\n\007channel\030\003 \001(\0162\026.m" +
      "pp.common.v1.Channel\022\023\n\013pipeline_id\030\004 \001(" +
      "\t\022\030\n\020pipeline_version\030\005 \001(\t\022\017\n\007node_id\030\006" +
      " \001(\t\022,\n\nstage_name\030\007 \001(\0162\030.mpp.common.v1" +
      ".StageName\022\032\n\022stage_execution_id\030\010 \001(\t\022\017" +
      "\n\007attempt\030\t \001(\005\022,\n\010deadline\030\n \001(\0132\032.goog" +
      "le.protobuf.Timestamp\022/\n\013message_ttl\030\013 \001" +
      "(\0132\032.google.protobuf.Timestamp\022O\n\017config" +
      "_versions\030\014 \003(\01326.mpp.common.v1.StageExe" +
      "cuteCommand.ConfigVersionsEntry\022\023\n\013trace" +
      "parent\030\r \001(\t\0223\n\013payload_ref\030\016 \001(\0132\036.mpp." +
      "common.v1.StagePayloadRef\022O\n\026destination" +
      "_resolution\030\024 \001(\0132-.mpp.common.v1.Destin" +
      "ationResolutionExtensionH\000\0220\n\006policy\030\025 \001" +
      "(\0132\036.mpp.common.v1.PolicyExtensionH\000\0222\n\007" +
      "billing\030\026 \001(\0132\037.mpp.common.v1.BillingExt" +
      "ensionH\000\0222\n\007routing\030\027 \001(\0132\037.mpp.common.v" +
      "1.RoutingExtensionH\000\0224\n\010delivery\030\030 \001(\0132 " +
      ".mpp.common.v1.DeliveryExtensionH\000\022Q\n\027de" +
      "livery_reconciliation\030\031 \001(\0132..mpp.common" +
      ".v1.DeliveryReconciliationExtensionH\000\0325\n" +
      "\023ConfigVersionsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
      "ue\030\002 \001(\003:\0028\001B\021\n\017stage_extension\"=\n\036Desti" +
      "nationResolutionExtension\022\033\n\023destination" +
      "_address\030\001 \001(\t\"/\n\017PolicyExtension\022\034\n\024res" +
      "olved_operator_id\030\001 \001(\t\"Y\n\020BillingExtens" +
      "ion\022\034\n\024resolved_operator_id\030\001 \001(\t\022\025\n\rseg" +
      "ment_count\030\002 \001(\005\022\020\n\010category\030\003 \001(\t\"0\n\020Ro" +
      "utingExtension\022\034\n\024resolved_operator_id\030\001" +
      " \001(\t\"g\n\021DeliveryExtension\022\020\n\010route_id\030\001 " +
      "\001(\t\022)\n\010protocol\030\002 \001(\0162\027.mpp.common.v1.Pr" +
      "otocol\022\025\n\rroute_version\030\003 \001(\t\"k\n\037Deliver" +
      "yReconciliationExtension\0222\n\022triggering_o" +
      "utcome\030\001 \001(\0162\026.mpp.common.v1.Outcome\022\024\n\014" +
      "queue_msg_id\030\002 \001(\t\"\321\005\n\023StageCompletedEve" +
      "nt\022\020\n\010event_id\030\001 \001(\t\022\022\n\nmessage_id\030\002 \001(\t" +
      "\022\032\n\022stage_execution_id\030\003 \001(\t\022\017\n\007attempt\030" +
      "\004 \001(\005\022,\n\nstage_name\030\005 \001(\0162\030.mpp.common.v" +
      "1.StageName\022\'\n\007outcome\030\006 \001(\0162\026.mpp.commo" +
      "n.v1.Outcome\022\023\n\013reason_code\030\007 \001(\t\022\021\n\tret" +
      "ryable\030\010 \001(\010\022/\n\013retry_after\030\t \001(\0132\032.goog" +
      "le.protobuf.Timestamp\022\023\n\013traceparent\030\n \001" +
      "(\t\0220\n\014completed_at\030\013 \001(\0132\032.google.protob" +
      "uf.Timestamp\022L\n\026destination_resolution\030\024" +
      " \001(\0132*.mpp.common.v1.DestinationResoluti" +
      "onResultH\000\022-\n\006policy\030\025 \001(\0132\033.mpp.common." +
      "v1.PolicyResultH\000\022/\n\007billing\030\026 \001(\0132\034.mpp" +
      ".common.v1.BillingResultH\000\022/\n\007routing\030\027 " +
      "\001(\0132\034.mpp.common.v1.RoutingResultH\000\0221\n\010d" +
      "elivery\030\030 \001(\0132\035.mpp.common.v1.DeliveryRe" +
      "sultH\000\022N\n\027delivery_reconciliation\030\031 \001(\0132" +
      "+.mpp.common.v1.DeliveryReconciliationRe" +
      "sultH\000B\016\n\014stage_result\";\n\033DestinationRes" +
      "olutionResult\022\034\n\024resolved_operator_id\030\001 " +
      "\001(\t\" \n\014PolicyResult\022\020\n\010category\030\001 \001(\t\"Z\n" +
      "\rBillingResult\022\021\n\tcharge_id\030\001 \001(\t\022\020\n\010cat" +
      "egory\030\004 \001(\t\022$\n\006amount\030\002 \001(\0132\024.mpp.common" +
      ".v1.Money\"c\n\rRoutingResult\022\020\n\010route_id\030\001" +
      " \001(\t\022)\n\010protocol\030\002 \001(\0162\027.mpp.common.v1.P" +
      "rotocol\022\025\n\rroute_version\030\003 \001(\t\"&\n\016Delive" +
      "ryResult\022\024\n\014queue_msg_id\030\001 \001(\t\"d\n\034Delive" +
      "ryReconciliationResult\022D\n\026reconciliation" +
      "_outcome\030\001 \001(\0162$.mpp.common.v1.Reconcili" +
      "ationOutcomeBP\n\"uz.mpp.platformcontracts" +
      ".common.v1P\001Z(mpp/platformcontracts/comm" +
      "on/v1;commonv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          uz.mpp.platformcontracts.common.v1.Enums.getDescriptor(),
          uz.mpp.platformcontracts.common.v1.Types.getDescriptor(),
        });
    internal_static_mpp_common_v1_StageExecuteCommand_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_mpp_common_v1_StageExecuteCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_StageExecuteCommand_descriptor,
        new java.lang.String[] { "EventId", "MessageId", "Channel", "PipelineId", "PipelineVersion", "NodeId", "StageName", "StageExecutionId", "Attempt", "Deadline", "MessageTtl", "ConfigVersions", "Traceparent", "PayloadRef", "DestinationResolution", "Policy", "Billing", "Routing", "Delivery", "DeliveryReconciliation", "StageExtension", });
    internal_static_mpp_common_v1_StageExecuteCommand_ConfigVersionsEntry_descriptor =
      internal_static_mpp_common_v1_StageExecuteCommand_descriptor.getNestedType(0);
    internal_static_mpp_common_v1_StageExecuteCommand_ConfigVersionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_StageExecuteCommand_ConfigVersionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mpp_common_v1_DestinationResolutionExtension_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_mpp_common_v1_DestinationResolutionExtension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_DestinationResolutionExtension_descriptor,
        new java.lang.String[] { "DestinationAddress", });
    internal_static_mpp_common_v1_PolicyExtension_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_mpp_common_v1_PolicyExtension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_PolicyExtension_descriptor,
        new java.lang.String[] { "ResolvedOperatorId", });
    internal_static_mpp_common_v1_BillingExtension_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_mpp_common_v1_BillingExtension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_BillingExtension_descriptor,
        new java.lang.String[] { "ResolvedOperatorId", "SegmentCount", "Category", });
    internal_static_mpp_common_v1_RoutingExtension_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_mpp_common_v1_RoutingExtension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_RoutingExtension_descriptor,
        new java.lang.String[] { "ResolvedOperatorId", });
    internal_static_mpp_common_v1_DeliveryExtension_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_mpp_common_v1_DeliveryExtension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_DeliveryExtension_descriptor,
        new java.lang.String[] { "RouteId", "Protocol", "RouteVersion", });
    internal_static_mpp_common_v1_DeliveryReconciliationExtension_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_mpp_common_v1_DeliveryReconciliationExtension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_DeliveryReconciliationExtension_descriptor,
        new java.lang.String[] { "TriggeringOutcome", "QueueMsgId", });
    internal_static_mpp_common_v1_StageCompletedEvent_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_mpp_common_v1_StageCompletedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_StageCompletedEvent_descriptor,
        new java.lang.String[] { "EventId", "MessageId", "StageExecutionId", "Attempt", "StageName", "Outcome", "ReasonCode", "Retryable", "RetryAfter", "Traceparent", "CompletedAt", "DestinationResolution", "Policy", "Billing", "Routing", "Delivery", "DeliveryReconciliation", "StageResult", });
    internal_static_mpp_common_v1_DestinationResolutionResult_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_mpp_common_v1_DestinationResolutionResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_DestinationResolutionResult_descriptor,
        new java.lang.String[] { "ResolvedOperatorId", });
    internal_static_mpp_common_v1_PolicyResult_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_mpp_common_v1_PolicyResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_PolicyResult_descriptor,
        new java.lang.String[] { "Category", });
    internal_static_mpp_common_v1_BillingResult_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_mpp_common_v1_BillingResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_BillingResult_descriptor,
        new java.lang.String[] { "ChargeId", "Category", "Amount", });
    internal_static_mpp_common_v1_RoutingResult_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_mpp_common_v1_RoutingResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_RoutingResult_descriptor,
        new java.lang.String[] { "RouteId", "Protocol", "RouteVersion", });
    internal_static_mpp_common_v1_DeliveryResult_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_mpp_common_v1_DeliveryResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_DeliveryResult_descriptor,
        new java.lang.String[] { "QueueMsgId", });
    internal_static_mpp_common_v1_DeliveryReconciliationResult_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_mpp_common_v1_DeliveryReconciliationResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_DeliveryReconciliationResult_descriptor,
        new java.lang.String[] { "ReconciliationOutcome", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    uz.mpp.platformcontracts.common.v1.Enums.getDescriptor();
    uz.mpp.platformcontracts.common.v1.Types.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
