// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/types.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

@com.google.protobuf.Generated
public final class Types extends com.google.protobuf.GeneratedFile {
  private Types() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Types");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_Money_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_Money_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_PartnerContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_PartnerContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_SmsPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_SmsPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_EmailPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_EmailPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_PushPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_PushPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_common_v1_StagePayloadRef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_common_v1_StagePayloadRef_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022common/types.proto\022\rmpp.common.v1\"3\n\005M" +
      "oney\022\025\n\rcurrency_code\030\001 \001(\t\022\023\n\013minor_uni" +
      "ts\030\002 \001(\003\"O\n\016PartnerContext\022\022\n\npartner_id" +
      "\030\001 \001(\t\022\026\n\016application_id\030\002 \001(\t\022\021\n\tsource" +
      "_ip\030\003 \001(\t\"c\n\nSmsPayload\022\016\n\006msisdn\030\001 \001(\t\022" +
      "\016\n\006sender\030\002 \001(\t\022\014\n\004body\030\003 \001(\t\022\020\n\010encodin" +
      "g\030\004 \001(\t\022\025\n\rsegment_count\030\005 \001(\005\"\024\n\014EmailP" +
      "ayloadJ\004\010\001\020\013\"\023\n\013PushPayloadJ\004\010\001\020\013\"@\n\017Sta" +
      "gePayloadRef\022\022\n\nmessage_id\030\001 \001(\t\022\031\n\021runt" +
      "ime_redis_key\030\002 \001(\tBP\n\"uz.mpp.platformco" +
      "ntracts.common.v1P\001Z(mpp/platformcontrac" +
      "ts/common/v1;commonv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mpp_common_v1_Money_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_mpp_common_v1_Money_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_Money_descriptor,
        new java.lang.String[] { "CurrencyCode", "MinorUnits", });
    internal_static_mpp_common_v1_PartnerContext_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_mpp_common_v1_PartnerContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_PartnerContext_descriptor,
        new java.lang.String[] { "PartnerId", "ApplicationId", "SourceIp", });
    internal_static_mpp_common_v1_SmsPayload_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_mpp_common_v1_SmsPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_SmsPayload_descriptor,
        new java.lang.String[] { "Msisdn", "Sender", "Body", "Encoding", "SegmentCount", });
    internal_static_mpp_common_v1_EmailPayload_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_mpp_common_v1_EmailPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_EmailPayload_descriptor,
        new java.lang.String[] { });
    internal_static_mpp_common_v1_PushPayload_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_mpp_common_v1_PushPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_PushPayload_descriptor,
        new java.lang.String[] { });
    internal_static_mpp_common_v1_StagePayloadRef_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_mpp_common_v1_StagePayloadRef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_common_v1_StagePayloadRef_descriptor,
        new java.lang.String[] { "MessageId", "RuntimeRedisKey", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
