// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/enums.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

/**
 * <pre>
 * Канал сообщения — независимое от протокола измерение (HLD §3.1.1).
 * Определяет, какой вариант StagePayload / MessageBody заполнен и какой
 * набор Policy/Billing-правил применяется.
 * </pre>
 *
 * Protobuf enum {@code mpp.common.v1.Channel}
 */
@com.google.protobuf.Generated
public enum Channel
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CHANNEL_UNSPECIFIED = 0;</code>
   */
  CHANNEL_UNSPECIFIED(0),
  /**
   * <code>CHANNEL_SMS = 1;</code>
   */
  CHANNEL_SMS(1),
  /**
   * <pre>
   * Зарезервировано, payload не специфицирован в этой версии контрактов.
   * </pre>
   *
   * <code>CHANNEL_EMAIL = 2;</code>
   */
  CHANNEL_EMAIL(2),
  /**
   * <pre>
   * Зарезервировано, payload не специфицирован в этой версии контрактов.
   * </pre>
   *
   * <code>CHANNEL_PUSH = 3;</code>
   */
  CHANNEL_PUSH(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Channel");
  }
  /**
   * <code>CHANNEL_UNSPECIFIED = 0;</code>
   */
  public static final int CHANNEL_UNSPECIFIED_VALUE = 0;
  /**
   * <code>CHANNEL_SMS = 1;</code>
   */
  public static final int CHANNEL_SMS_VALUE = 1;
  /**
   * <pre>
   * Зарезервировано, payload не специфицирован в этой версии контрактов.
   * </pre>
   *
   * <code>CHANNEL_EMAIL = 2;</code>
   */
  public static final int CHANNEL_EMAIL_VALUE = 2;
  /**
   * <pre>
   * Зарезервировано, payload не специфицирован в этой версии контрактов.
   * </pre>
   *
   * <code>CHANNEL_PUSH = 3;</code>
   */
  public static final int CHANNEL_PUSH_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Channel valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Channel forNumber(int value) {
    switch (value) {
      case 0: return CHANNEL_UNSPECIFIED;
      case 1: return CHANNEL_SMS;
      case 2: return CHANNEL_EMAIL;
      case 3: return CHANNEL_PUSH;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Channel>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Channel> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Channel>() {
          public Channel findValueByNumber(int number) {
            return Channel.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return uz.mpp.platformcontracts.common.v1.Enums.getDescriptor().getEnumType(0);
  }

  private static final Channel[] VALUES = values();

  public static Channel valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Channel(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:mpp.common.v1.Channel)
}

