// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/stage_contract.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

@com.google.protobuf.Generated
public interface DeliveryReconciliationResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.common.v1.DeliveryReconciliationResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mpp.common.v1.ReconciliationOutcome reconciliation_outcome = 1;</code>
   * @return The enum numeric value on the wire for reconciliationOutcome.
   */
  int getReconciliationOutcomeValue();
  /**
   * <code>.mpp.common.v1.ReconciliationOutcome reconciliation_outcome = 1;</code>
   * @return The reconciliationOutcome.
   */
  uz.mpp.platformcontracts.common.v1.ReconciliationOutcome getReconciliationOutcome();
}
