// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/stage_contract.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

/**
 * Protobuf type {@code mpp.common.v1.DestinationResolutionExtension}
 */
@com.google.protobuf.Generated
public final class DestinationResolutionExtension extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:mpp.common.v1.DestinationResolutionExtension)
    DestinationResolutionExtensionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "DestinationResolutionExtension");
  }
  // Use DestinationResolutionExtension.newBuilder() to construct.
  private DestinationResolutionExtension(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DestinationResolutionExtension() {
    destinationAddress_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_DestinationResolutionExtension_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_DestinationResolutionExtension_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_DestinationResolutionExtension_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension.class, uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension.Builder.class);
  }

  public static final int DESTINATION_ADDRESS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object destinationAddress_ = "";
  /**
   * <pre>
   * Адрес назначения — msisdn для SMS; поле общее по имени для будущих
   * каналов (email-адрес, push device token), не msisdn-специфичное.
   * </pre>
   *
   * <code>string destination_address = 1;</code>
   * @return The destinationAddress.
   */
  @java.lang.Override
  public java.lang.String getDestinationAddress() {
    java.lang.Object ref = destinationAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationAddress_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Адрес назначения — msisdn для SMS; поле общее по имени для будущих
   * каналов (email-адрес, push device token), не msisdn-специфичное.
   * </pre>
   *
   * <code>string destination_address = 1;</code>
   * @return The bytes for destinationAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDestinationAddressBytes() {
    java.lang.Object ref = destinationAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(destinationAddress_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, destinationAddress_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(destinationAddress_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, destinationAddress_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension)) {
      return super.equals(obj);
    }
    uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension other = (uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension) obj;

    if (!getDestinationAddress()
        .equals(other.getDestinationAddress())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DESTINATION_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationAddress().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mpp.common.v1.DestinationResolutionExtension}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mpp.common.v1.DestinationResolutionExtension)
      uz.mpp.platformcontracts.common.v1.DestinationResolutionExtensionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_DestinationResolutionExtension_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_DestinationResolutionExtension_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension.class, uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension.Builder.class);
    }

    // Construct using uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      destinationAddress_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uz.mpp.platformcontracts.common.v1.StageContract.internal_static_mpp_common_v1_DestinationResolutionExtension_descriptor;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension getDefaultInstanceForType() {
      return uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension.getDefaultInstance();
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension build() {
      uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension buildPartial() {
      uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension result = new uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.destinationAddress_ = destinationAddress_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension) {
        return mergeFrom((uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension other) {
      if (other == uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension.getDefaultInstance()) return this;
      if (!other.getDestinationAddress().isEmpty()) {
        destinationAddress_ = other.destinationAddress_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              destinationAddress_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object destinationAddress_ = "";
    /**
     * <pre>
     * Адрес назначения — msisdn для SMS; поле общее по имени для будущих
     * каналов (email-адрес, push device token), не msisdn-специфичное.
     * </pre>
     *
     * <code>string destination_address = 1;</code>
     * @return The destinationAddress.
     */
    public java.lang.String getDestinationAddress() {
      java.lang.Object ref = destinationAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Адрес назначения — msisdn для SMS; поле общее по имени для будущих
     * каналов (email-адрес, push device token), не msisdn-специфичное.
     * </pre>
     *
     * <code>string destination_address = 1;</code>
     * @return The bytes for destinationAddress.
     */
    public com.google.protobuf.ByteString
        getDestinationAddressBytes() {
      java.lang.Object ref = destinationAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Адрес назначения — msisdn для SMS; поле общее по имени для будущих
     * каналов (email-адрес, push device token), не msisdn-специфичное.
     * </pre>
     *
     * <code>string destination_address = 1;</code>
     * @param value The destinationAddress to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationAddress(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      destinationAddress_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Адрес назначения — msisdn для SMS; поле общее по имени для будущих
     * каналов (email-адрес, push device token), не msisdn-специфичное.
     * </pre>
     *
     * <code>string destination_address = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestinationAddress() {
      destinationAddress_ = getDefaultInstance().getDestinationAddress();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Адрес назначения — msisdn для SMS; поле общее по имени для будущих
     * каналов (email-адрес, push device token), не msisdn-специфичное.
     * </pre>
     *
     * <code>string destination_address = 1;</code>
     * @param value The bytes for destinationAddress to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      destinationAddress_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:mpp.common.v1.DestinationResolutionExtension)
  }

  // @@protoc_insertion_point(class_scope:mpp.common.v1.DestinationResolutionExtension)
  private static final uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension();
  }

  public static uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DestinationResolutionExtension>
      PARSER = new com.google.protobuf.AbstractParser<DestinationResolutionExtension>() {
    @java.lang.Override
    public DestinationResolutionExtension parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DestinationResolutionExtension> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DestinationResolutionExtension> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

