// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/types.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

/**
 * <pre>
 * Зарезервировано под будущий канал — payload не специфицируется
 * в этой версии контрактов (HLD §26).
 * </pre>
 *
 * Protobuf type {@code mpp.common.v1.EmailPayload}
 */
@com.google.protobuf.Generated
public final class EmailPayload extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:mpp.common.v1.EmailPayload)
    EmailPayloadOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "EmailPayload");
  }
  // Use EmailPayload.newBuilder() to construct.
  private EmailPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EmailPayload() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uz.mpp.platformcontracts.common.v1.Types.internal_static_mpp_common_v1_EmailPayload_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return uz.mpp.platformcontracts.common.v1.Types.internal_static_mpp_common_v1_EmailPayload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uz.mpp.platformcontracts.common.v1.Types.internal_static_mpp_common_v1_EmailPayload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uz.mpp.platformcontracts.common.v1.EmailPayload.class, uz.mpp.platformcontracts.common.v1.EmailPayload.Builder.class);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getUnknownFields().writeTo(output);
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uz.mpp.platformcontracts.common.v1.EmailPayload)) {
      return super.equals(obj);
    }
    uz.mpp.platformcontracts.common.v1.EmailPayload other = (uz.mpp.platformcontracts.common.v1.EmailPayload) obj;

    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uz.mpp.platformcontracts.common.v1.EmailPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.common.v1.EmailPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.EmailPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.common.v1.EmailPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.EmailPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.common.v1.EmailPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.EmailPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.common.v1.EmailPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static uz.mpp.platformcontracts.common.v1.EmailPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static uz.mpp.platformcontracts.common.v1.EmailPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.common.v1.EmailPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.common.v1.EmailPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uz.mpp.platformcontracts.common.v1.EmailPayload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Зарезервировано под будущий канал — payload не специфицируется
   * в этой версии контрактов (HLD §26).
   * </pre>
   *
   * Protobuf type {@code mpp.common.v1.EmailPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mpp.common.v1.EmailPayload)
      uz.mpp.platformcontracts.common.v1.EmailPayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uz.mpp.platformcontracts.common.v1.Types.internal_static_mpp_common_v1_EmailPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uz.mpp.platformcontracts.common.v1.Types.internal_static_mpp_common_v1_EmailPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uz.mpp.platformcontracts.common.v1.EmailPayload.class, uz.mpp.platformcontracts.common.v1.EmailPayload.Builder.class);
    }

    // Construct using uz.mpp.platformcontracts.common.v1.EmailPayload.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uz.mpp.platformcontracts.common.v1.Types.internal_static_mpp_common_v1_EmailPayload_descriptor;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.EmailPayload getDefaultInstanceForType() {
      return uz.mpp.platformcontracts.common.v1.EmailPayload.getDefaultInstance();
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.EmailPayload build() {
      uz.mpp.platformcontracts.common.v1.EmailPayload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.common.v1.EmailPayload buildPartial() {
      uz.mpp.platformcontracts.common.v1.EmailPayload result = new uz.mpp.platformcontracts.common.v1.EmailPayload(this);
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uz.mpp.platformcontracts.common.v1.EmailPayload) {
        return mergeFrom((uz.mpp.platformcontracts.common.v1.EmailPayload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uz.mpp.platformcontracts.common.v1.EmailPayload other) {
      if (other == uz.mpp.platformcontracts.common.v1.EmailPayload.getDefaultInstance()) return this;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    // @@protoc_insertion_point(builder_scope:mpp.common.v1.EmailPayload)
  }

  // @@protoc_insertion_point(class_scope:mpp.common.v1.EmailPayload)
  private static final uz.mpp.platformcontracts.common.v1.EmailPayload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uz.mpp.platformcontracts.common.v1.EmailPayload();
  }

  public static uz.mpp.platformcontracts.common.v1.EmailPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmailPayload>
      PARSER = new com.google.protobuf.AbstractParser<EmailPayload>() {
    @java.lang.Override
    public EmailPayload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EmailPayload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmailPayload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uz.mpp.platformcontracts.common.v1.EmailPayload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

