// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/types.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

@com.google.protobuf.Generated
public interface PartnerContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.common.v1.PartnerContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string partner_id = 1;</code>
   * @return The partnerId.
   */
  java.lang.String getPartnerId();
  /**
   * <code>string partner_id = 1;</code>
   * @return The bytes for partnerId.
   */
  com.google.protobuf.ByteString
      getPartnerIdBytes();

  /**
   * <code>string application_id = 2;</code>
   * @return The applicationId.
   */
  java.lang.String getApplicationId();
  /**
   * <code>string application_id = 2;</code>
   * @return The bytes for applicationId.
   */
  com.google.protobuf.ByteString
      getApplicationIdBytes();

  /**
   * <pre>
   * IP, с которого пришёл запрос — для аудита, не для допуска
   * (allowlist-проверка уже применена на момент заполнения этого поля).
   * </pre>
   *
   * <code>string source_ip = 3;</code>
   * @return The sourceIp.
   */
  java.lang.String getSourceIp();
  /**
   * <pre>
   * IP, с которого пришёл запрос — для аудита, не для допуска
   * (allowlist-проверка уже применена на момент заполнения этого поля).
   * </pre>
   *
   * <code>string source_ip = 3;</code>
   * @return The bytes for sourceIp.
   */
  com.google.protobuf.ByteString
      getSourceIpBytes();
}
