// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/stage_contract.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

@com.google.protobuf.Generated
public interface PolicyExtensionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.common.v1.PolicyExtension)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Заполняется Pipeline Engine из результата DestinationResolution —
   * обязательный предшественник (HLD §5.3).
   * </pre>
   *
   * <code>string resolved_operator_id = 1;</code>
   * @return The resolvedOperatorId.
   */
  java.lang.String getResolvedOperatorId();
  /**
   * <pre>
   * Заполняется Pipeline Engine из результата DestinationResolution —
   * обязательный предшественник (HLD §5.3).
   * </pre>
   *
   * <code>string resolved_operator_id = 1;</code>
   * @return The bytes for resolvedOperatorId.
   */
  com.google.protobuf.ByteString
      getResolvedOperatorIdBytes();
}
