// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/stage_contract.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

@com.google.protobuf.Generated
public interface PolicyResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.common.v1.PolicyResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Присвоенная категория. Всегда заполнена, включая случай REJECTED:
   * "UNTEMPLATED" — нет совпадения с шаблоном, но партнёр разрешил
   * продолжить; "BLOCKED" — Policy отклонил сообщение (любая из 8 проверок,
   * HLD §5.3/§15 — единая категория и тариф независимо от конкретной
   * причины отклонения). Billing всегда получает непустую category.
   * </pre>
   *
   * <code>string category = 1;</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <pre>
   * Присвоенная категория. Всегда заполнена, включая случай REJECTED:
   * "UNTEMPLATED" — нет совпадения с шаблоном, но партнёр разрешил
   * продолжить; "BLOCKED" — Policy отклонил сообщение (любая из 8 проверок,
   * HLD §5.3/§15 — единая категория и тариф независимо от конкретной
   * причины отклонения). Billing всегда получает непустую category.
   * </pre>
   *
   * <code>string category = 1;</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();
}
