// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/types.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

@com.google.protobuf.Generated
public interface PushPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.common.v1.PushPayload)
    com.google.protobuf.MessageOrBuilder {
}
