// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/types.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

@com.google.protobuf.Generated
public interface SmsPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.common.v1.SmsPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msisdn = 1;</code>
   * @return The msisdn.
   */
  java.lang.String getMsisdn();
  /**
   * <code>string msisdn = 1;</code>
   * @return The bytes for msisdn.
   */
  com.google.protobuf.ByteString
      getMsisdnBytes();

  /**
   * <code>string sender = 2;</code>
   * @return The sender.
   */
  java.lang.String getSender();
  /**
   * <code>string sender = 2;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <pre>
   * Присутствует только в IncomingMessage и в Runtime Redis msgctx;
   * в StageExecuteCommand НЕ передаётся, см. StagePayloadRef.
   * </pre>
   *
   * <code>string body = 3;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <pre>
   * Присутствует только в IncomingMessage и в Runtime Redis msgctx;
   * в StageExecuteCommand НЕ передаётся, см. StagePayloadRef.
   * </pre>
   *
   * <code>string body = 3;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <code>string encoding = 4;</code>
   * @return The encoding.
   */
  java.lang.String getEncoding();
  /**
   * <code>string encoding = 4;</code>
   * @return The bytes for encoding.
   */
  com.google.protobuf.ByteString
      getEncodingBytes();

  /**
   * <pre>
   * Посчитано один раз Pipeline Engine при кэшировании контекста —
   * передаётся Billing полем в команде без чтения msgctx.
   * </pre>
   *
   * <code>int32 segment_count = 5;</code>
   * @return The segmentCount.
   */
  int getSegmentCount();
}
