// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/enums.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

/**
 * <pre>
 * Зарегистрированные типы стадий (HLD §5.3). Порядок значений — не порядок
 * исполнения; фактический порядок определяет Pipeline Engine по графу,
 * кроме DESTINATION_RESOLUTION, которая всегда идёт первой.
 * </pre>
 *
 * Protobuf enum {@code mpp.common.v1.StageName}
 */
@com.google.protobuf.Generated
public enum StageName
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>STAGE_NAME_UNSPECIFIED = 0;</code>
   */
  STAGE_NAME_UNSPECIFIED(0),
  /**
   * <code>STAGE_NAME_DESTINATION_RESOLUTION = 1;</code>
   */
  STAGE_NAME_DESTINATION_RESOLUTION(1),
  /**
   * <code>STAGE_NAME_POLICY = 2;</code>
   */
  STAGE_NAME_POLICY(2),
  /**
   * <code>STAGE_NAME_BILLING = 3;</code>
   */
  STAGE_NAME_BILLING(3),
  /**
   * <code>STAGE_NAME_ROUTING = 4;</code>
   */
  STAGE_NAME_ROUTING(4),
  /**
   * <code>STAGE_NAME_DELIVERY = 5;</code>
   */
  STAGE_NAME_DELIVERY(5),
  /**
   * <code>STAGE_NAME_DELIVERY_RECONCILIATION = 6;</code>
   */
  STAGE_NAME_DELIVERY_RECONCILIATION(6),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "StageName");
  }
  /**
   * <code>STAGE_NAME_UNSPECIFIED = 0;</code>
   */
  public static final int STAGE_NAME_UNSPECIFIED_VALUE = 0;
  /**
   * <code>STAGE_NAME_DESTINATION_RESOLUTION = 1;</code>
   */
  public static final int STAGE_NAME_DESTINATION_RESOLUTION_VALUE = 1;
  /**
   * <code>STAGE_NAME_POLICY = 2;</code>
   */
  public static final int STAGE_NAME_POLICY_VALUE = 2;
  /**
   * <code>STAGE_NAME_BILLING = 3;</code>
   */
  public static final int STAGE_NAME_BILLING_VALUE = 3;
  /**
   * <code>STAGE_NAME_ROUTING = 4;</code>
   */
  public static final int STAGE_NAME_ROUTING_VALUE = 4;
  /**
   * <code>STAGE_NAME_DELIVERY = 5;</code>
   */
  public static final int STAGE_NAME_DELIVERY_VALUE = 5;
  /**
   * <code>STAGE_NAME_DELIVERY_RECONCILIATION = 6;</code>
   */
  public static final int STAGE_NAME_DELIVERY_RECONCILIATION_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static StageName valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static StageName forNumber(int value) {
    switch (value) {
      case 0: return STAGE_NAME_UNSPECIFIED;
      case 1: return STAGE_NAME_DESTINATION_RESOLUTION;
      case 2: return STAGE_NAME_POLICY;
      case 3: return STAGE_NAME_BILLING;
      case 4: return STAGE_NAME_ROUTING;
      case 5: return STAGE_NAME_DELIVERY;
      case 6: return STAGE_NAME_DELIVERY_RECONCILIATION;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<StageName>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      StageName> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<StageName>() {
          public StageName findValueByNumber(int number) {
            return StageName.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return uz.mpp.platformcontracts.common.v1.Enums.getDescriptor().getEnumType(2);
  }

  private static final StageName[] VALUES = values();

  public static StageName valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private StageName(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:mpp.common.v1.StageName)
}

