// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/stage_contract.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

@com.google.protobuf.Generated
public interface StageExecuteCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.common.v1.StageExecuteCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event_id = 1;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string event_id = 1;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>string message_id = 2;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <code>string message_id = 2;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>.mpp.common.v1.Channel channel = 3;</code>
   * @return The enum numeric value on the wire for channel.
   */
  int getChannelValue();
  /**
   * <code>.mpp.common.v1.Channel channel = 3;</code>
   * @return The channel.
   */
  uz.mpp.platformcontracts.common.v1.Channel getChannel();

  /**
   * <code>string pipeline_id = 4;</code>
   * @return The pipelineId.
   */
  java.lang.String getPipelineId();
  /**
   * <code>string pipeline_id = 4;</code>
   * @return The bytes for pipelineId.
   */
  com.google.protobuf.ByteString
      getPipelineIdBytes();

  /**
   * <code>string pipeline_version = 5;</code>
   * @return The pipelineVersion.
   */
  java.lang.String getPipelineVersion();
  /**
   * <code>string pipeline_version = 5;</code>
   * @return The bytes for pipelineVersion.
   */
  com.google.protobuf.ByteString
      getPipelineVersionBytes();

  /**
   * <code>string node_id = 6;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 6;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>.mpp.common.v1.StageName stage_name = 7;</code>
   * @return The enum numeric value on the wire for stageName.
   */
  int getStageNameValue();
  /**
   * <code>.mpp.common.v1.StageName stage_name = 7;</code>
   * @return The stageName.
   */
  uz.mpp.platformcontracts.common.v1.StageName getStageName();

  /**
   * <pre>
   * Стабилен на всё логическое выполнение узла, не меняется при retry —
   * единственный ключ идемпотентности (HLD §4).
   * </pre>
   *
   * <code>string stage_execution_id = 8;</code>
   * @return The stageExecutionId.
   */
  java.lang.String getStageExecutionId();
  /**
   * <pre>
   * Стабилен на всё логическое выполнение узла, не меняется при retry —
   * единственный ключ идемпотентности (HLD §4).
   * </pre>
   *
   * <code>string stage_execution_id = 8;</code>
   * @return The bytes for stageExecutionId.
   */
  com.google.protobuf.ByteString
      getStageExecutionIdBytes();

  /**
   * <pre>
   * 1 при первой попытке; растёт при retry, но НЕ является ключом
   * идемпотентности.
   * </pre>
   *
   * <code>int32 attempt = 9;</code>
   * @return The attempt.
   */
  int getAttempt();

  /**
   * <code>.google.protobuf.Timestamp deadline = 10;</code>
   * @return Whether the deadline field is set.
   */
  boolean hasDeadline();
  /**
   * <code>.google.protobuf.Timestamp deadline = 10;</code>
   * @return The deadline.
   */
  com.google.protobuf.Timestamp getDeadline();
  /**
   * <code>.google.protobuf.Timestamp deadline = 10;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDeadlineOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp message_ttl = 11;</code>
   * @return Whether the messageTtl field is set.
   */
  boolean hasMessageTtl();
  /**
   * <code>.google.protobuf.Timestamp message_ttl = 11;</code>
   * @return The messageTtl.
   */
  com.google.protobuf.Timestamp getMessageTtl();
  /**
   * <code>.google.protobuf.Timestamp message_ttl = 11;</code>
   */
  com.google.protobuf.TimestampOrBuilder getMessageTtlOrBuilder();

  /**
   * <pre>
   * Версии конфигурации, применённые к этому сообщению — фиксируются
   * на момент диспетчеризации, не пересматриваются при повторной публикации
   * новой конфигурации (HLD §7.1).
   * </pre>
   *
   * <code>map&lt;string, int64&gt; config_versions = 12;</code>
   */
  int getConfigVersionsCount();
  /**
   * <pre>
   * Версии конфигурации, применённые к этому сообщению — фиксируются
   * на момент диспетчеризации, не пересматриваются при повторной публикации
   * новой конфигурации (HLD §7.1).
   * </pre>
   *
   * <code>map&lt;string, int64&gt; config_versions = 12;</code>
   */
  boolean containsConfigVersions(
      java.lang.String key);
  /**
   * Use {@link #getConfigVersionsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Long>
  getConfigVersions();
  /**
   * <pre>
   * Версии конфигурации, применённые к этому сообщению — фиксируются
   * на момент диспетчеризации, не пересматриваются при повторной публикации
   * новой конфигурации (HLD §7.1).
   * </pre>
   *
   * <code>map&lt;string, int64&gt; config_versions = 12;</code>
   */
  java.util.Map<java.lang.String, java.lang.Long>
  getConfigVersionsMap();
  /**
   * <pre>
   * Версии конфигурации, применённые к этому сообщению — фиксируются
   * на момент диспетчеризации, не пересматриваются при повторной публикации
   * новой конфигурации (HLD §7.1).
   * </pre>
   *
   * <code>map&lt;string, int64&gt; config_versions = 12;</code>
   */
  long getConfigVersionsOrDefault(
      java.lang.String key,
      long defaultValue);
  /**
   * <pre>
   * Версии конфигурации, применённые к этому сообщению — фиксируются
   * на момент диспетчеризации, не пересматриваются при повторной публикации
   * новой конфигурации (HLD §7.1).
   * </pre>
   *
   * <code>map&lt;string, int64&gt; config_versions = 12;</code>
   */
  long getConfigVersionsOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * W3C Trace Context.
   * </pre>
   *
   * <code>string traceparent = 13;</code>
   * @return The traceparent.
   */
  java.lang.String getTraceparent();
  /**
   * <pre>
   * W3C Trace Context.
   * </pre>
   *
   * <code>string traceparent = 13;</code>
   * @return The bytes for traceparent.
   */
  com.google.protobuf.ByteString
      getTraceparentBytes();

  /**
   * <code>.mpp.common.v1.StagePayloadRef payload_ref = 14;</code>
   * @return Whether the payloadRef field is set.
   */
  boolean hasPayloadRef();
  /**
   * <code>.mpp.common.v1.StagePayloadRef payload_ref = 14;</code>
   * @return The payloadRef.
   */
  uz.mpp.platformcontracts.common.v1.StagePayloadRef getPayloadRef();
  /**
   * <code>.mpp.common.v1.StagePayloadRef payload_ref = 14;</code>
   */
  uz.mpp.platformcontracts.common.v1.StagePayloadRefOrBuilder getPayloadRefOrBuilder();

  /**
   * <code>.mpp.common.v1.DestinationResolutionExtension destination_resolution = 20;</code>
   * @return Whether the destinationResolution field is set.
   */
  boolean hasDestinationResolution();
  /**
   * <code>.mpp.common.v1.DestinationResolutionExtension destination_resolution = 20;</code>
   * @return The destinationResolution.
   */
  uz.mpp.platformcontracts.common.v1.DestinationResolutionExtension getDestinationResolution();
  /**
   * <code>.mpp.common.v1.DestinationResolutionExtension destination_resolution = 20;</code>
   */
  uz.mpp.platformcontracts.common.v1.DestinationResolutionExtensionOrBuilder getDestinationResolutionOrBuilder();

  /**
   * <code>.mpp.common.v1.PolicyExtension policy = 21;</code>
   * @return Whether the policy field is set.
   */
  boolean hasPolicy();
  /**
   * <code>.mpp.common.v1.PolicyExtension policy = 21;</code>
   * @return The policy.
   */
  uz.mpp.platformcontracts.common.v1.PolicyExtension getPolicy();
  /**
   * <code>.mpp.common.v1.PolicyExtension policy = 21;</code>
   */
  uz.mpp.platformcontracts.common.v1.PolicyExtensionOrBuilder getPolicyOrBuilder();

  /**
   * <code>.mpp.common.v1.BillingExtension billing = 22;</code>
   * @return Whether the billing field is set.
   */
  boolean hasBilling();
  /**
   * <code>.mpp.common.v1.BillingExtension billing = 22;</code>
   * @return The billing.
   */
  uz.mpp.platformcontracts.common.v1.BillingExtension getBilling();
  /**
   * <code>.mpp.common.v1.BillingExtension billing = 22;</code>
   */
  uz.mpp.platformcontracts.common.v1.BillingExtensionOrBuilder getBillingOrBuilder();

  /**
   * <code>.mpp.common.v1.RoutingExtension routing = 23;</code>
   * @return Whether the routing field is set.
   */
  boolean hasRouting();
  /**
   * <code>.mpp.common.v1.RoutingExtension routing = 23;</code>
   * @return The routing.
   */
  uz.mpp.platformcontracts.common.v1.RoutingExtension getRouting();
  /**
   * <code>.mpp.common.v1.RoutingExtension routing = 23;</code>
   */
  uz.mpp.platformcontracts.common.v1.RoutingExtensionOrBuilder getRoutingOrBuilder();

  /**
   * <code>.mpp.common.v1.DeliveryExtension delivery = 24;</code>
   * @return Whether the delivery field is set.
   */
  boolean hasDelivery();
  /**
   * <code>.mpp.common.v1.DeliveryExtension delivery = 24;</code>
   * @return The delivery.
   */
  uz.mpp.platformcontracts.common.v1.DeliveryExtension getDelivery();
  /**
   * <code>.mpp.common.v1.DeliveryExtension delivery = 24;</code>
   */
  uz.mpp.platformcontracts.common.v1.DeliveryExtensionOrBuilder getDeliveryOrBuilder();

  /**
   * <code>.mpp.common.v1.DeliveryReconciliationExtension delivery_reconciliation = 25;</code>
   * @return Whether the deliveryReconciliation field is set.
   */
  boolean hasDeliveryReconciliation();
  /**
   * <code>.mpp.common.v1.DeliveryReconciliationExtension delivery_reconciliation = 25;</code>
   * @return The deliveryReconciliation.
   */
  uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtension getDeliveryReconciliation();
  /**
   * <code>.mpp.common.v1.DeliveryReconciliationExtension delivery_reconciliation = 25;</code>
   */
  uz.mpp.platformcontracts.common.v1.DeliveryReconciliationExtensionOrBuilder getDeliveryReconciliationOrBuilder();

  uz.mpp.platformcontracts.common.v1.StageExecuteCommand.StageExtensionCase getStageExtensionCase();
}
