// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/types.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.common.v1;

@com.google.protobuf.Generated
public interface StagePayloadRefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.common.v1.StagePayloadRef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message_id = 1;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <code>string message_id = 1;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <pre>
   * Ключ в Runtime Redis: msgctx:{message_id}. Явно вынесен полем,
   * а не собирается конкатенацией на стороне потребителя.
   * </pre>
   *
   * <code>string runtime_redis_key = 2;</code>
   * @return The runtimeRedisKey.
   */
  java.lang.String getRuntimeRedisKey();
  /**
   * <pre>
   * Ключ в Runtime Redis: msgctx:{message_id}. Явно вынесен полем,
   * а не собирается конкатенацией на стороне потребителя.
   * </pre>
   *
   * <code>string runtime_redis_key = 2;</code>
   * @return The bytes for runtimeRedisKey.
   */
  com.google.protobuf.ByteString
      getRuntimeRedisKeyBytes();
}
