// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/config_and_control.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.events.v1;

@com.google.protobuf.Generated
public final class ConfigAndControl extends com.google.protobuf.GeneratedFile {
  private ConfigAndControl() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ConfigAndControl");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_events_v1_ConfigChangeEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_events_v1_ConfigChangeEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mpp_events_v1_ExecutionControlRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mpp_events_v1_ExecutionControlRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037events/config_and_control.proto\022\rmpp.e" +
      "vents.v1\032\037google/protobuf/timestamp.prot" +
      "o\032\022common/enums.proto\"\303\001\n\021ConfigChangeEv" +
      "ent\0224\n\013entity_type\030\001 \001(\0162\037.mpp.common.v1" +
      ".ConfigEntityType\022\021\n\tentity_id\030\002 \001(\t\022\017\n\007" +
      "version\030\003 \001(\003\022\024\n\014payload_json\030\004 \001(\014\022\016\n\006s" +
      "tatus\030\005 \001(\t\022.\n\ncreated_at\030\006 \001(\0132\032.google" +
      ".protobuf.Timestamp\"\304\002\n\026ExecutionControl" +
      "Record\0223\n\005scope\030\001 \001(\0162$.mpp.common.v1.Ex" +
      "ecutionControlScope\022\020\n\010scope_id\030\002 \001(\t\0223\n" +
      "\005state\030\003 \001(\0162$.mpp.common.v1.ExecutionCo" +
      "ntrolState\022\026\n\016admission_rate\030\004 \001(\001\022\025\n\rdi" +
      "spatch_rate\030\005 \001(\001\022\016\n\006reason\030\006 \001(\t\022\017\n\007ver" +
      "sion\030\007 \001(\003\022.\n\nexpires_at\030\010 \001(\0132\032.google." +
      "protobuf.Timestamp\022.\n\ncreated_at\030\t \001(\0132\032" +
      ".google.protobuf.TimestampBP\n\"uz.mpp.pla" +
      "tformcontracts.events.v1P\001Z(mpp/platform" +
      "contracts/events/v1;eventsv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          uz.mpp.platformcontracts.common.v1.Enums.getDescriptor(),
        });
    internal_static_mpp_events_v1_ConfigChangeEvent_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_mpp_events_v1_ConfigChangeEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_events_v1_ConfigChangeEvent_descriptor,
        new java.lang.String[] { "EntityType", "EntityId", "Version", "PayloadJson", "Status", "CreatedAt", });
    internal_static_mpp_events_v1_ExecutionControlRecord_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_mpp_events_v1_ExecutionControlRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mpp_events_v1_ExecutionControlRecord_descriptor,
        new java.lang.String[] { "Scope", "ScopeId", "State", "AdmissionRate", "DispatchRate", "Reason", "Version", "ExpiresAt", "CreatedAt", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    uz.mpp.platformcontracts.common.v1.Enums.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
