// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/config_and_control.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.events.v1;

@com.google.protobuf.Generated
public interface ConfigChangeEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.events.v1.ConfigChangeEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mpp.common.v1.ConfigEntityType entity_type = 1;</code>
   * @return The enum numeric value on the wire for entityType.
   */
  int getEntityTypeValue();
  /**
   * <code>.mpp.common.v1.ConfigEntityType entity_type = 1;</code>
   * @return The entityType.
   */
  uz.mpp.platformcontracts.common.v1.ConfigEntityType getEntityType();

  /**
   * <code>string entity_id = 2;</code>
   * @return The entityId.
   */
  java.lang.String getEntityId();
  /**
   * <code>string entity_id = 2;</code>
   * @return The bytes for entityId.
   */
  com.google.protobuf.ByteString
      getEntityIdBytes();

  /**
   * <code>int64 version = 3;</code>
   * @return The version.
   */
  long getVersion();

  /**
   * <pre>
   * Сериализованный JSON — конкретная форма см. в LLD соответствующего
   * потребителя (Policy ruleset, route table, tariff и т.д.).
   * </pre>
   *
   * <code>bytes payload_json = 4;</code>
   * @return The payloadJson.
   */
  com.google.protobuf.ByteString getPayloadJson();

  /**
   * <pre>
   * "active" | "archived"
   * </pre>
   *
   * <code>string status = 5;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * "active" | "archived"
   * </pre>
   *
   * <code>string status = 5;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();
}
