// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/config_and_control.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.events.v1;

@com.google.protobuf.Generated
public interface ExecutionControlRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.events.v1.ExecutionControlRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mpp.common.v1.ExecutionControlScope scope = 1;</code>
   * @return The enum numeric value on the wire for scope.
   */
  int getScopeValue();
  /**
   * <code>.mpp.common.v1.ExecutionControlScope scope = 1;</code>
   * @return The scope.
   */
  uz.mpp.platformcontracts.common.v1.ExecutionControlScope getScope();

  /**
   * <pre>
   * Пусто для scope = GLOBAL; иначе partner_id / stage_name /
   * "partner_id:stage_name" / operator_route_id в зависимости от scope.
   * </pre>
   *
   * <code>string scope_id = 2;</code>
   * @return The scopeId.
   */
  java.lang.String getScopeId();
  /**
   * <pre>
   * Пусто для scope = GLOBAL; иначе partner_id / stage_name /
   * "partner_id:stage_name" / operator_route_id в зависимости от scope.
   * </pre>
   *
   * <code>string scope_id = 2;</code>
   * @return The bytes for scopeId.
   */
  com.google.protobuf.ByteString
      getScopeIdBytes();

  /**
   * <code>.mpp.common.v1.ExecutionControlState state = 3;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <code>.mpp.common.v1.ExecutionControlState state = 3;</code>
   * @return The state.
   */
  uz.mpp.platformcontracts.common.v1.ExecutionControlState getState();

  /**
   * <pre>
   * 0.0–1.0, доля от номинальной пропускной способности scope.
   * </pre>
   *
   * <code>double admission_rate = 4;</code>
   * @return The admissionRate.
   */
  double getAdmissionRate();

  /**
   * <code>double dispatch_rate = 5;</code>
   * @return The dispatchRate.
   */
  double getDispatchRate();

  /**
   * <code>string reason = 6;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 6;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>int64 version = 7;</code>
   * @return The version.
   */
  long getVersion();

  /**
   * <pre>
   * Пусто для не-ручных (автоматических) записей.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expires_at = 8;</code>
   * @return Whether the expiresAt field is set.
   */
  boolean hasExpiresAt();
  /**
   * <pre>
   * Пусто для не-ручных (автоматических) записей.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expires_at = 8;</code>
   * @return The expiresAt.
   */
  com.google.protobuf.Timestamp getExpiresAt();
  /**
   * <pre>
   * Пусто для не-ручных (автоматических) записей.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expires_at = 8;</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpiresAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp created_at = 9;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 9;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 9;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();
}
