// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/scheduler_events.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.events.v1;

/**
 * <pre>
 * Задача повторной доставки уведомления — публикуется в notification.retry
 * Background Lane'ом (HLD §19).
 * </pre>
 *
 * Protobuf type {@code mpp.events.v1.NotificationRetryTask}
 */
@com.google.protobuf.Generated
public final class NotificationRetryTask extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:mpp.events.v1.NotificationRetryTask)
    NotificationRetryTaskOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "NotificationRetryTask");
  }
  // Use NotificationRetryTask.newBuilder() to construct.
  private NotificationRetryTask(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private NotificationRetryTask() {
    messageId_ = "";
    lifecycleEventId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uz.mpp.platformcontracts.events.v1.SchedulerEvents.internal_static_mpp_events_v1_NotificationRetryTask_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return uz.mpp.platformcontracts.events.v1.SchedulerEvents.internal_static_mpp_events_v1_NotificationRetryTask_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uz.mpp.platformcontracts.events.v1.SchedulerEvents.internal_static_mpp_events_v1_NotificationRetryTask_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uz.mpp.platformcontracts.events.v1.NotificationRetryTask.class, uz.mpp.platformcontracts.events.v1.NotificationRetryTask.Builder.class);
  }

  private int bitField0_;
  public static final int MESSAGE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object messageId_ = "";
  /**
   * <code>string message_id = 1;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public java.lang.String getMessageId() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageId_ = s;
      return s;
    }
  }
  /**
   * <code>string message_id = 1;</code>
   * @return The bytes for messageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageIdBytes() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LIFECYCLE_EVENT_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lifecycleEventId_ = "";
  /**
   * <code>string lifecycle_event_id = 2;</code>
   * @return The lifecycleEventId.
   */
  @java.lang.Override
  public java.lang.String getLifecycleEventId() {
    java.lang.Object ref = lifecycleEventId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lifecycleEventId_ = s;
      return s;
    }
  }
  /**
   * <code>string lifecycle_event_id = 2;</code>
   * @return The bytes for lifecycleEventId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLifecycleEventIdBytes() {
    java.lang.Object ref = lifecycleEventId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lifecycleEventId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTEMPT_FIELD_NUMBER = 3;
  private int attempt_ = 0;
  /**
   * <code>int32 attempt = 3;</code>
   * @return The attempt.
   */
  @java.lang.Override
  public int getAttempt() {
    return attempt_;
  }

  public static final int RETRY_AT_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp retryAt_;
  /**
   * <code>.google.protobuf.Timestamp retry_at = 4;</code>
   * @return Whether the retryAt field is set.
   */
  @java.lang.Override
  public boolean hasRetryAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp retry_at = 4;</code>
   * @return The retryAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getRetryAt() {
    return retryAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : retryAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp retry_at = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getRetryAtOrBuilder() {
    return retryAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : retryAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, messageId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lifecycleEventId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, lifecycleEventId_);
    }
    if (attempt_ != 0) {
      output.writeInt32(3, attempt_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getRetryAt());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, messageId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lifecycleEventId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, lifecycleEventId_);
    }
    if (attempt_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, attempt_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getRetryAt());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uz.mpp.platformcontracts.events.v1.NotificationRetryTask)) {
      return super.equals(obj);
    }
    uz.mpp.platformcontracts.events.v1.NotificationRetryTask other = (uz.mpp.platformcontracts.events.v1.NotificationRetryTask) obj;

    if (!getMessageId()
        .equals(other.getMessageId())) return false;
    if (!getLifecycleEventId()
        .equals(other.getLifecycleEventId())) return false;
    if (getAttempt()
        != other.getAttempt()) return false;
    if (hasRetryAt() != other.hasRetryAt()) return false;
    if (hasRetryAt()) {
      if (!getRetryAt()
          .equals(other.getRetryAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMessageId().hashCode();
    hash = (37 * hash) + LIFECYCLE_EVENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getLifecycleEventId().hashCode();
    hash = (37 * hash) + ATTEMPT_FIELD_NUMBER;
    hash = (53 * hash) + getAttempt();
    if (hasRetryAt()) {
      hash = (37 * hash) + RETRY_AT_FIELD_NUMBER;
      hash = (53 * hash) + getRetryAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uz.mpp.platformcontracts.events.v1.NotificationRetryTask parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.events.v1.NotificationRetryTask parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.events.v1.NotificationRetryTask parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.events.v1.NotificationRetryTask parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.events.v1.NotificationRetryTask parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uz.mpp.platformcontracts.events.v1.NotificationRetryTask parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.events.v1.NotificationRetryTask parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.events.v1.NotificationRetryTask parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static uz.mpp.platformcontracts.events.v1.NotificationRetryTask parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static uz.mpp.platformcontracts.events.v1.NotificationRetryTask parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uz.mpp.platformcontracts.events.v1.NotificationRetryTask parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uz.mpp.platformcontracts.events.v1.NotificationRetryTask parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uz.mpp.platformcontracts.events.v1.NotificationRetryTask prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Задача повторной доставки уведомления — публикуется в notification.retry
   * Background Lane'ом (HLD §19).
   * </pre>
   *
   * Protobuf type {@code mpp.events.v1.NotificationRetryTask}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mpp.events.v1.NotificationRetryTask)
      uz.mpp.platformcontracts.events.v1.NotificationRetryTaskOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uz.mpp.platformcontracts.events.v1.SchedulerEvents.internal_static_mpp_events_v1_NotificationRetryTask_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uz.mpp.platformcontracts.events.v1.SchedulerEvents.internal_static_mpp_events_v1_NotificationRetryTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uz.mpp.platformcontracts.events.v1.NotificationRetryTask.class, uz.mpp.platformcontracts.events.v1.NotificationRetryTask.Builder.class);
    }

    // Construct using uz.mpp.platformcontracts.events.v1.NotificationRetryTask.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRetryAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      messageId_ = "";
      lifecycleEventId_ = "";
      attempt_ = 0;
      retryAt_ = null;
      if (retryAtBuilder_ != null) {
        retryAtBuilder_.dispose();
        retryAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uz.mpp.platformcontracts.events.v1.SchedulerEvents.internal_static_mpp_events_v1_NotificationRetryTask_descriptor;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.events.v1.NotificationRetryTask getDefaultInstanceForType() {
      return uz.mpp.platformcontracts.events.v1.NotificationRetryTask.getDefaultInstance();
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.events.v1.NotificationRetryTask build() {
      uz.mpp.platformcontracts.events.v1.NotificationRetryTask result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uz.mpp.platformcontracts.events.v1.NotificationRetryTask buildPartial() {
      uz.mpp.platformcontracts.events.v1.NotificationRetryTask result = new uz.mpp.platformcontracts.events.v1.NotificationRetryTask(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(uz.mpp.platformcontracts.events.v1.NotificationRetryTask result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.messageId_ = messageId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.lifecycleEventId_ = lifecycleEventId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.attempt_ = attempt_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.retryAt_ = retryAtBuilder_ == null
            ? retryAt_
            : retryAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uz.mpp.platformcontracts.events.v1.NotificationRetryTask) {
        return mergeFrom((uz.mpp.platformcontracts.events.v1.NotificationRetryTask)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uz.mpp.platformcontracts.events.v1.NotificationRetryTask other) {
      if (other == uz.mpp.platformcontracts.events.v1.NotificationRetryTask.getDefaultInstance()) return this;
      if (!other.getMessageId().isEmpty()) {
        messageId_ = other.messageId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getLifecycleEventId().isEmpty()) {
        lifecycleEventId_ = other.lifecycleEventId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getAttempt() != 0) {
        setAttempt(other.getAttempt());
      }
      if (other.hasRetryAt()) {
        mergeRetryAt(other.getRetryAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              messageId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              lifecycleEventId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              attempt_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  internalGetRetryAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object messageId_ = "";
    /**
     * <code>string message_id = 1;</code>
     * @return The messageId.
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message_id = 1;</code>
     * @return The bytes for messageId.
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message_id = 1;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      messageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string message_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      messageId_ = getDefaultInstance().getMessageId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string message_id = 1;</code>
     * @param value The bytes for messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      messageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object lifecycleEventId_ = "";
    /**
     * <code>string lifecycle_event_id = 2;</code>
     * @return The lifecycleEventId.
     */
    public java.lang.String getLifecycleEventId() {
      java.lang.Object ref = lifecycleEventId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lifecycleEventId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lifecycle_event_id = 2;</code>
     * @return The bytes for lifecycleEventId.
     */
    public com.google.protobuf.ByteString
        getLifecycleEventIdBytes() {
      java.lang.Object ref = lifecycleEventId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lifecycleEventId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lifecycle_event_id = 2;</code>
     * @param value The lifecycleEventId to set.
     * @return This builder for chaining.
     */
    public Builder setLifecycleEventId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lifecycleEventId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string lifecycle_event_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLifecycleEventId() {
      lifecycleEventId_ = getDefaultInstance().getLifecycleEventId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string lifecycle_event_id = 2;</code>
     * @param value The bytes for lifecycleEventId to set.
     * @return This builder for chaining.
     */
    public Builder setLifecycleEventIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lifecycleEventId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int attempt_ ;
    /**
     * <code>int32 attempt = 3;</code>
     * @return The attempt.
     */
    @java.lang.Override
    public int getAttempt() {
      return attempt_;
    }
    /**
     * <code>int32 attempt = 3;</code>
     * @param value The attempt to set.
     * @return This builder for chaining.
     */
    public Builder setAttempt(int value) {

      attempt_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 attempt = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAttempt() {
      bitField0_ = (bitField0_ & ~0x00000004);
      attempt_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp retryAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> retryAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp retry_at = 4;</code>
     * @return Whether the retryAt field is set.
     */
    public boolean hasRetryAt() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp retry_at = 4;</code>
     * @return The retryAt.
     */
    public com.google.protobuf.Timestamp getRetryAt() {
      if (retryAtBuilder_ == null) {
        return retryAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : retryAt_;
      } else {
        return retryAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp retry_at = 4;</code>
     */
    public Builder setRetryAt(com.google.protobuf.Timestamp value) {
      if (retryAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        retryAt_ = value;
      } else {
        retryAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp retry_at = 4;</code>
     */
    public Builder setRetryAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (retryAtBuilder_ == null) {
        retryAt_ = builderForValue.build();
      } else {
        retryAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp retry_at = 4;</code>
     */
    public Builder mergeRetryAt(com.google.protobuf.Timestamp value) {
      if (retryAtBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          retryAt_ != null &&
          retryAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getRetryAtBuilder().mergeFrom(value);
        } else {
          retryAt_ = value;
        }
      } else {
        retryAtBuilder_.mergeFrom(value);
      }
      if (retryAt_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp retry_at = 4;</code>
     */
    public Builder clearRetryAt() {
      bitField0_ = (bitField0_ & ~0x00000008);
      retryAt_ = null;
      if (retryAtBuilder_ != null) {
        retryAtBuilder_.dispose();
        retryAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp retry_at = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getRetryAtBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetRetryAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp retry_at = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getRetryAtOrBuilder() {
      if (retryAtBuilder_ != null) {
        return retryAtBuilder_.getMessageOrBuilder();
      } else {
        return retryAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : retryAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp retry_at = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetRetryAtFieldBuilder() {
      if (retryAtBuilder_ == null) {
        retryAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getRetryAt(),
                getParentForChildren(),
                isClean());
        retryAt_ = null;
      }
      return retryAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:mpp.events.v1.NotificationRetryTask)
  }

  // @@protoc_insertion_point(class_scope:mpp.events.v1.NotificationRetryTask)
  private static final uz.mpp.platformcontracts.events.v1.NotificationRetryTask DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uz.mpp.platformcontracts.events.v1.NotificationRetryTask();
  }

  public static uz.mpp.platformcontracts.events.v1.NotificationRetryTask getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NotificationRetryTask>
      PARSER = new com.google.protobuf.AbstractParser<NotificationRetryTask>() {
    @java.lang.Override
    public NotificationRetryTask parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NotificationRetryTask> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NotificationRetryTask> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uz.mpp.platformcontracts.events.v1.NotificationRetryTask getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

