// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/scheduler_events.proto
// Protobuf Java Version: 4.35.1

package uz.mpp.platformcontracts.events.v1;

@com.google.protobuf.Generated
public interface SchedulerBackgroundTaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mpp.events.v1.SchedulerBackgroundTask)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mpp.common.v1.BackgroundTaskType task_type = 1;</code>
   * @return The enum numeric value on the wire for taskType.
   */
  int getTaskTypeValue();
  /**
   * <code>.mpp.common.v1.BackgroundTaskType task_type = 1;</code>
   * @return The taskType.
   */
  uz.mpp.platformcontracts.common.v1.BackgroundTaskType getTaskType();

  /**
   * <pre>
   * Для DLR_CORRELATION_RETRY — event_id исходного operator.dlr;
   * для NOTIFICATION_RETRY — event_id исходного message.lifecycle.
   * </pre>
   *
   * <code>string source_event_id = 2;</code>
   * @return The sourceEventId.
   */
  java.lang.String getSourceEventId();
  /**
   * <pre>
   * Для DLR_CORRELATION_RETRY — event_id исходного operator.dlr;
   * для NOTIFICATION_RETRY — event_id исходного message.lifecycle.
   * </pre>
   *
   * <code>string source_event_id = 2;</code>
   * @return The bytes for sourceEventId.
   */
  com.google.protobuf.ByteString
      getSourceEventIdBytes();

  /**
   * <code>int32 attempt = 3;</code>
   * @return The attempt.
   */
  int getAttempt();

  /**
   * <code>.google.protobuf.Timestamp due_at = 4;</code>
   * @return Whether the dueAt field is set.
   */
  boolean hasDueAt();
  /**
   * <code>.google.protobuf.Timestamp due_at = 4;</code>
   * @return The dueAt.
   */
  com.google.protobuf.Timestamp getDueAt();
  /**
   * <code>.google.protobuf.Timestamp due_at = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDueAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp deadline = 5;</code>
   * @return Whether the deadline field is set.
   */
  boolean hasDeadline();
  /**
   * <code>.google.protobuf.Timestamp deadline = 5;</code>
   * @return The deadline.
   */
  com.google.protobuf.Timestamp getDeadline();
  /**
   * <code>.google.protobuf.Timestamp deadline = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDeadlineOrBuilder();

  /**
   * <pre>
   * Разрешённый список: "operator.dlr.unresolved" | "notification.retry" —
   * не произвольная строка (HLD §14, защита от использования Scheduler
   * как открытого редиректа внутри Kafka).
   * </pre>
   *
   * <code>string target_topic = 6;</code>
   * @return The targetTopic.
   */
  java.lang.String getTargetTopic();
  /**
   * <pre>
   * Разрешённый список: "operator.dlr.unresolved" | "notification.retry" —
   * не произвольная строка (HLD §14, защита от использования Scheduler
   * как открытого редиректа внутри Kafka).
   * </pre>
   *
   * <code>string target_topic = 6;</code>
   * @return The bytes for targetTopic.
   */
  com.google.protobuf.ByteString
      getTargetTopicBytes();
}
