/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApplications"];
        put?: never;
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateApplication"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/senders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSenders"];
        put?: never;
        post: operations["createSender"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/senders/{sender_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSenderStatus"];
        trace?: never;
    };
    "/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCredentials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/credentials/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWebhook"];
        put: operations["updateWebhook"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/webhook/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Аутентифицированный прокси в template-management-service — partner_id всегда берётся из JWT на бэкенде, query-параметр partner_id здесь не имеет смысла отправлять (будет проигнорирован). */
        get: operations["listTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Единственный тред вызывающего партнёра (partner_id всегда из JWT на бэкенде) — нет query-параметра partner_id, в отличие от backoffice-ui's эквивалентного эндпоинта (там partner_id в path, админ видит все треды). */
        get: operations["listChatMessages"];
        put?: never;
        post: operations["sendChatMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApplicationAuth: {
            /** @enum {string} */
            type: "API_KEY" | "MTLS" | "SMPP_BIND";
            credential_ref: string;
        };
        Application: {
            application_id: string;
            display_name: string;
            auth: components["schemas"]["ApplicationAuth"];
            ip_allowlist?: string[];
            rate_limit_tps: number;
            allowed_channels: ("SMS" | "EMAIL" | "PUSH")[];
            notification_callback_url?: string;
        };
        CreateApplicationRequest: {
            application_id: string;
            display_name: string;
            auth: components["schemas"]["ApplicationAuth"];
            ip_allowlist?: string[];
            rate_limit_tps: number;
            allowed_channels: ("SMS" | "EMAIL" | "PUSH")[];
        };
        UpdateApplicationRequest: {
            display_name: string;
            ip_allowlist?: string[];
            rate_limit_tps: number;
            allowed_channels: ("SMS" | "EMAIL" | "PUSH")[];
            notification_callback_url?: string;
        };
        Sender: {
            sender_id: string;
            /** @enum {string} */
            type: "ALPHANAME" | "SHORT_NUMBER";
            /** @enum {string} */
            status: "active" | "archived";
        };
        CreateSenderRequest: {
            sender_id: string;
            /** @enum {string} */
            type: "ALPHANAME" | "SHORT_NUMBER";
        };
        UpdateSenderStatusRequest: {
            /** @enum {string} */
            status: "active" | "archived";
        };
        IssuedSecretSummary: {
            /** Format: int64 */
            id: number;
            partner_id: string;
            application_id: string;
            credential_ref: string;
            secret_version: number;
            /** @enum {string} */
            status: "active" | "revoked";
            /** Format: date-time */
            issued_at?: string;
            issued_by?: string;
        };
        RotateCredentialResponse: {
            credential_ref: string;
            secret_version: number;
            /** @description Show-once — присутствует ТОЛЬКО в ответе на этот вызов, нигде больше не сохраняется/не показывается повторно. */
            plaintext_secret: string;
            /** Format: date-time */
            issued_at?: string;
        };
        WebhookConfig: {
            application_id: string;
            notification_callback_url: string;
        };
        UpdateWebhookRequest: {
            notification_callback_url: string;
        };
        WebhookTestResult: {
            http_status: number;
            /** Format: int64 */
            latency_ms: number;
        };
        Template: {
            template_id: string;
            partner_id: string;
            operator_id?: string | null;
            sender_id?: string | null;
            channel: string;
            category: string;
            pattern: string;
            version: number;
            status: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TemplatesListResponse: {
            templates: components["schemas"]["Template"][];
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
        };
        ChatMessage: {
            /** Format: int64 */
            id: number;
            partner_id: string;
            /** @enum {string} */
            sender_type: "partner" | "admin";
            sender_id: string;
            body: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            read_at?: string;
        };
        ListChatMessagesResponse: {
            messages: components["schemas"]["ChatMessage"][];
        };
        SendChatMessageRequest: {
            body: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listApplications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"][];
                };
            };
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    updateApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApplicationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    listSenders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sender"][];
                };
            };
        };
    };
    createSender: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSenderRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sender"];
                };
            };
        };
    };
    updateSenderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sender_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSenderStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sender"];
                };
            };
        };
    };
    listCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedSecretSummary"][];
                };
            };
        };
    };
    rotateCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateCredentialResponse"];
                };
            };
        };
    };
    getWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookConfig"];
                };
            };
        };
    };
    updateWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWebhookRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookConfig"];
                };
            };
        };
    };
    testWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookTestResult"];
                };
            };
        };
    };
    listTemplates: {
        parameters: {
            query?: {
                sender_id?: string;
                category?: string;
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplatesListResponse"];
                };
            };
        };
    };
    listChatMessages: {
        parameters: {
            query?: {
                since?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListChatMessagesResponse"];
                };
            };
        };
    };
    sendChatMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendChatMessageRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"];
                };
            };
        };
    };
}
