/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description from и to обязательны (RFC3339). */
        get: operations["getSpendSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tariff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTariff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRecurringPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LedgerEntry: {
            /** Format: int64 */
            id: number;
            charge_id: string;
            account_id: string;
            partner_id: string;
            /** @description NUMERIC(18,4) как строка — не парсить как float, только для отображения/дальнейшего decimal-разбора. */
            amount: string;
            currency: string;
            /** @enum {string} */
            entry_type: "charge" | "compensating";
            source_charge_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        SpendSummary: {
            currency: string;
            /** @description netto (charge - compensating) как строка, та же NUMERIC-осторожность, что LedgerEntry.amount */
            total: string;
        };
        PricePerSegment: {
            [key: string]: number;
        };
        ServicePackage: {
            /** Format: int64 */
            segments: number;
            /** Format: int64 */
            price: number;
        };
        RecurringChargesSpec: {
            /** Format: int64 */
            alphaname_monthly_fee?: number;
            service_sms_package?: components["schemas"]["ServicePackage"];
        };
        BillingTariff: {
            currency: string;
            price_per_segment: components["schemas"]["PricePerSegment"];
            default_category: string;
            recurring_charges?: components["schemas"]["RecurringChargesSpec"];
        };
        TariffResponse: {
            /** @description false — для партнёра не опубликован собственный BILLING_TARIFF, применяется платформенный дефолт billing-service; конкретные цифры дефолта этому сервису недоступны (зашиты в образ billing-service) — не показывать угаданные значения, только факт "используется дефолт". */
            custom: boolean;
            tariff?: components["schemas"]["BillingTariff"];
        };
        RecurringChargePreview: {
            sender_id: string;
            /** @enum {string} */
            type: "ALPHANAME" | "SHORT_NUMBER";
            /** @description false — тариф для партнёра не опубликован, показывать "уточняется", не подставлять 0/угаданное значение. */
            fee_known: boolean;
            /** Format: int64 */
            fee?: number;
            currency?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLedger: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerEntry"][];
                };
            };
        };
    };
    getSpendSummary: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendSummary"][];
                };
            };
        };
    };
    getTariff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TariffResponse"];
                };
            };
        };
    };
    getRecurringPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringChargePreview"][];
                };
            };
        };
    };
}
